version: '3.7'
services:
  yacd:
      image:  ghcr.io/haishanh/yacd:master
      ports:
        - 1234:80
      restart: unless-stopped
      # 限制日志大小
      logging:
        driver: "json-file"
        options:
          max-size: "10m"
          max-file: "3"
# clash dashboard
