from __future__ import annotations

import argparse
import json
import os
import pwd
import re
import shlex
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path
from typing import Any

from .common import (
    AuditConfig,
    COLOR_GREEN,
    COLOR_RED,
    COLOR_YELLOW,
    CLIArgumentParser,
    CLIError,
    adopt_versioned_binary_layout,
    atomic_symlink,
    atomic_write_text,
    command_exists,
    color_text,
    current_script_dir,
    detect_arch,
    download_file,
    ensure_default_path,
    extract_zip,
    fetch_url,
    hcl_string,
    http_status,
    install_text,
    kept_binary_versions,
    linked_binary_path,
    log_error,
    log_info,
    log_success,
    log_warn,
    missing_subcommand,
    prune_binary_versions,
    require_command,
    require_linux,
    run,
    run_root,
    run_with_audit,
    safe_remove_path,
    sha256_file,
    terminal_status_prefix,
    version_tuple,
    versioned_binary_path,
    with_default_scheme,
)


VAULT_MANAGER_CMD = os.environ.get("VAULT_MANAGER_CMD", "vault-manager")
DEFAULT_VAULT_VERSION = "2.0.0"
VAULT_USER = "vault"
VAULT_GROUP = "vault"
VAULT_ROOT_DIR = Path("/opt/vault")
BIN_DIR = VAULT_ROOT_DIR / "bin"
BIN_PATH = BIN_DIR / "vault"
BINARY_VERSION_DIR = BIN_DIR / "versions"
BIN_ENTRY = Path("/usr/local/bin/vault")
CONFIG_DIR = VAULT_ROOT_DIR / "etc" / "vault.d"
CONFIG_FILE = CONFIG_DIR / "config.hcl"
TLS_DIR = CONFIG_DIR / "tls"
TLS_CA_CERT_FILE = TLS_DIR / "ca.crt"
TLS_CERT_FILE = TLS_DIR / "server.crt"
TLS_KEY_FILE = TLS_DIR / "server.key"
CLIENT_ENV_FILE = CONFIG_DIR / "client.env"
STATE_DIR = VAULT_ROOT_DIR / "data" / "vault"
DATA_DIR = STATE_DIR / "raft"
INIT_DIR = VAULT_ROOT_DIR / "init"
DEFAULT_INIT_FILE = INIT_DIR / "vault-init.json"
SYSTEMD_SERVICE = Path("/etc/systemd/system/vault.service")
TOOL_DIR = VAULT_ROOT_DIR / "lib" / "vault-init-tools"
TOOL_STATE_DIR = VAULT_ROOT_DIR / "data" / "vault-init-tools"
TOOL_LOG_DIR = VAULT_ROOT_DIR / "log" / "vault-init-tools"
TOOL_PATH = BIN_DIR / "vault-manager"
TOOL_ENTRY = Path("/usr/local/bin/vault-manager")
LEGACY_TOOL_ENTRY = Path("/usr/local/sbin/vault-manager")
TOOL_VERSION_FILE = TOOL_DIR / "VERSION"
TOOL_MANIFEST_FILE = TOOL_DIR / "MANIFEST.sha256"
INSTALL_METADATA_FILE = TOOL_STATE_DIR / "install.json"
AUDIT_LOG_FILE = TOOL_LOG_DIR / "manager.audit.log"
STATE_POINTER_FILE = STATE_DIR / ".managed-by-vault-init-tools"
RELEASE_INDEX_URL = "https://releases.hashicorp.com/vault/"
DEFAULT_VAULT_ADDR = "http://127.0.0.1:8200"
DEFAULT_LISTEN_ADDRESS = "0.0.0.0:8200"
DEFAULT_CLUSTER_ADDRESS = "0.0.0.0:8201"
DEFAULT_CLUSTER_ADDR = "http://127.0.0.1:8201"
LOCAL_NO_PROXY = "127.0.0.1,localhost,::1"
MANAGED_MARKER = "# Managed by tools/vault/vault-manager"
# accepted when reading, so a node installed by an older manager is still recognised
LEGACY_MANAGED_MARKERS = (
    "# Managed by tools/vault/manager.sh",
    "# Managed by vault.sh",
)
ACL_ENV_MARKER = "# Generated by vault-manager"
CERT_EXPIRY_WARN_DAYS = 30


def normalize_version(version: str) -> str:
    value = version.removeprefix("v")
    if not re.match(r"^[0-9]+[.][0-9]+[.][0-9]+$", value):
        raise CLIError(f"Invalid Vault version: {version}")
    return value


def parse_binary_version(output: str) -> str:
    """The version a vault binary reports, or "" when the output is unexpected."""
    match = re.search(r"Vault v([0-9]+[.][0-9]+[.][0-9]+)", output)
    return match.group(1) if match else ""


def installed_binary_version() -> str:
    """What the binary on this node reports, which upgrade trusts over metadata."""
    if not BIN_PATH.is_file():
        return ""
    return parse_binary_version(run([str(BIN_PATH), "version"], capture=True, check=False).stdout or "")


def fetch_latest_version() -> str:
    html = fetch_url(RELEASE_INDEX_URL, timeout=60).decode("utf-8", errors="replace")
    versions = re.findall(r'href="/vault/([0-9]+\.[0-9]+\.[0-9]+)/"', html)
    if not versions:
        raise CLIError("Failed to resolve latest Vault version")
    return normalize_version(versions[0])


def resolve_version(requested: str | None) -> str:
    if requested and requested != "latest":
        return normalize_version(requested)
    try:
        latest = fetch_latest_version()
        log_success(f"Resolved latest Vault version: {latest}")
        return latest
    except Exception:
        log_warn(f"Failed to resolve latest Vault version, fallback to {DEFAULT_VAULT_VERSION}")
        return DEFAULT_VAULT_VERSION


def resolve_upgrade_target(requested: str) -> str:
    """Resolve what to upgrade to, failing rather than guessing.

    resolve_version falls back to the pinned default when the release index is
    unreachable. That is fine for a fresh install, but here it would move a
    running node onto a version nobody asked for.
    """
    if requested and requested != "latest":
        return normalize_version(requested)
    try:
        latest = fetch_latest_version()
    except CLIError:
        raise
    except Exception as exc:
        raise CLIError(f"Cannot resolve the latest Vault version: {exc}. "
                       f"Pass --version to pick one explicitly") from exc
    log_success(f"Resolved latest Vault version: {latest}")
    return latest


def is_managed_file(path: Path) -> bool:
    if not path.is_file():
        return False
    try:
        with path.open("r", encoding="utf-8") as handle:
            first_line = handle.readline().rstrip("\n")
    except OSError:
        return False
    return first_line == MANAGED_MARKER or first_line in LEGACY_MANAGED_MARKERS


def ensure_managed_or_absent(path: Path) -> None:
    if path.exists() and not is_managed_file(path):
        raise CLIError(f"Refuse to manage non-managed file: {path}")


def doctor_check(status: str, message: str) -> None:
    labels = {
        "OK": (terminal_status_prefix(), COLOR_GREEN),
        "WARN": ("WARN", COLOR_YELLOW),
        "FAIL": ("FAIL", COLOR_RED),
        "INFO": ("INFO", ""),
    }
    label, color = labels.get(status, (status, ""))
    prefix = f"{label:<5}"
    print(f"{color_text(prefix, color) if color else prefix} {message}")


def doctor_info(message: str) -> None:
    """Report an effective setting. Informational only; never counted as a failure."""
    doctor_check("INFO", message)


def hcl_block_body(text: str, block: str) -> str:
    """Return the body of a `<block> ... {` ... `}` section from the managed config."""
    match = re.search(rf'(?m)^\s*{re.escape(block)}\s*(?:"[^"]*"\s*)?\{{', text)
    if not match:
        return ""
    start = text.index("{", match.start())
    depth = 0
    for index in range(start, len(text)):
        if text[index] == "{":
            depth += 1
        elif text[index] == "}":
            depth -= 1
            if depth == 0:
                return text[start + 1:index]
    return ""


def hcl_text_value(text: str, key: str) -> str:
    match = re.search(rf'(?m)^\s*{re.escape(key)}\s*=\s*(".*?"|true|false|\S+)', text)
    return match.group(1).strip().strip('"') if match else ""


def read_config_text() -> str:
    try:
        return CONFIG_FILE.read_text(encoding="utf-8")
    except OSError:
        return ""


def unset_label(value: str) -> str:
    return value if value else "<unset>"


def config_values() -> dict[str, str]:
    text = read_config_text()
    if not text:
        return {}
    listener = hcl_block_body(text, "listener")
    storage = hcl_block_body(text, "storage")
    return {
        "api_addr": hcl_text_value(text, "api_addr"),
        "cluster_addr": hcl_text_value(text, "cluster_addr"),
        "ui": hcl_text_value(text, "ui"),
        "disable_mlock": hcl_text_value(text, "disable_mlock"),
        "listen_address": hcl_text_value(listener, "address"),
        "cluster_address": hcl_text_value(listener, "cluster_address"),
        "tls_disable": hcl_text_value(listener, "tls_disable"),
        "tls_cert_file": hcl_text_value(listener, "tls_cert_file"),
        "tls_key_file": hcl_text_value(listener, "tls_key_file"),
        "storage_path": hcl_text_value(storage, "path"),
        "node_id": hcl_text_value(storage, "node_id"),
    }


def client_env_value(name: str) -> str:
    try:
        lines = CLIENT_ENV_FILE.read_text(encoding="utf-8").splitlines()
    except OSError:
        return ""
    for line in lines:
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, raw_value = stripped.split("=", 1)
        if key.strip() == name:
            return raw_value.strip().strip("'\"")
    return ""


def read_install_metadata() -> dict[str, Any]:
    try:
        data = json.loads(INSTALL_METADATA_FILE.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    return data if isinstance(data, dict) else {}


def read_installed_vault_version() -> str:
    version = read_install_metadata().get("vault_version")
    if isinstance(version, str) and version.strip():
        return version.strip()
    try:
        for line in TOOL_VERSION_FILE.read_text(encoding="utf-8").splitlines():
            key, sep, value = line.partition("=")
            if sep and key == "vault_version" and value.strip():
                return value.strip()
    except OSError:
        pass
    return "unknown"


class VaultClient:
    """Resolved connection settings for the vault CLI.

    Precedence: explicit flags, then the environment, then the client.env
    that install writes, then the built-in default.
    """

    def __init__(self, args: argparse.Namespace | None = None) -> None:
        self.address = (
            getattr(args, "addr", "") or os.environ.get("VAULT_ADDR", "")
            or client_env_value("VAULT_ADDR") or DEFAULT_VAULT_ADDR
        )
        self.ca_cert = (
            getattr(args, "ca_cert", "") or os.environ.get("VAULT_CACERT", "")
            or client_env_value("VAULT_CACERT")
        )
        self.namespace = getattr(args, "namespace", "") or os.environ.get("VAULT_NAMESPACE", "")
        self.token_file = getattr(args, "token_file", "") or ""

    def token(self) -> str:
        if self.token_file:
            token = read_token_file(Path(self.token_file))
            if not token:
                raise CLIError(f"Token file does not contain a token: {self.token_file}")
            return token
        return os.environ.get("VAULT_TOKEN", "")

    def env(self) -> dict[str, str]:
        env = os.environ.copy()
        env["VAULT_ADDR"] = self.address
        env["no_proxy"] = LOCAL_NO_PROXY
        env["NO_PROXY"] = LOCAL_NO_PROXY
        if self.ca_cert:
            env["VAULT_CACERT"] = self.ca_cert
        if self.namespace:
            env["VAULT_NAMESPACE"] = self.namespace
        token = self.token()
        if token:
            env["VAULT_TOKEN"] = token
        else:
            env.pop("VAULT_TOKEN", None)
        return env

    def run(self, command: list[str], *, capture: bool = False, check: bool = True) -> subprocess.CompletedProcess[str]:
        if not BIN_PATH.is_file():
            raise CLIError(f"Vault binary not found: {BIN_PATH}. Please run install first")
        return run([str(BIN_PATH), *command], env=self.env(), capture=capture, check=check)

    def status_json(self) -> dict[str, Any]:
        if not BIN_PATH.is_file():
            return {}
        result = self.run(["status", "-format=json"], capture=True, check=False)
        try:
            data = json.loads(result.stdout or "{}")
        except json.JSONDecodeError:
            return {}
        return data if isinstance(data, dict) else {}

    def health_url(self) -> str:
        return f"{with_default_scheme(self.address, 'http').rstrip('/')}/v1/sys/health"


def read_token_file(path: Path) -> str:
    """Accept either the JSON that init writes or a plain token file."""
    if not path.is_file():
        raise CLIError(f"Token file not found: {path}")
    raw = path.read_text(encoding="utf-8").strip()
    if not raw:
        return ""
    try:
        data = json.loads(raw)
    except json.JSONDecodeError:
        return raw.splitlines()[0].strip()
    if not isinstance(data, dict):
        return ""
    for key in ("root_token", "initial_root_token", "token"):
        value = data.get(key)
        if isinstance(value, str) and value:
            return value
    return ""


def unseal_keys_from_file(path: Path) -> list[str]:
    if not path.is_file():
        raise CLIError(f"Keys file is not a regular file: {path}")
    if not os.access(path, os.R_OK):
        raise CLIError(f"Keys file is not readable: {path}")
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except OSError as exc:
        raise CLIError(f"Failed to open keys file: {exc}") from exc
    except json.JSONDecodeError as exc:
        raise CLIError(f"Failed to parse keys file JSON: {exc}") from exc
    if not isinstance(data, dict):
        return []
    keys = data.get("unseal_keys_b64") or data.get("unseal_keys_hex") or []
    return [key for key in keys if isinstance(key, str) and key]


def target_acl_file() -> Path:
    target_user = os.environ.get("SUDO_USER") or pwd.getpwuid(os.getuid()).pw_name
    try:
        target_home = Path(pwd.getpwnam(target_user).pw_dir)
    except KeyError:
        target_home = Path.home()
    if not target_home.is_dir():
        target_home = Path.home()
    return target_home / "vault.acl"


def write_acl_env_file(client: VaultClient, token: str) -> None:
    if not token:
        log_warn("Vault root token not found in init output; skip vault.acl generation")
        return
    acl_file = target_acl_file()
    lines = [
        ACL_ENV_MARKER,
        "# Source this file to use the initialized Vault root token.",
        f"export VAULT_ADDR={shlex.quote(client.address)}",
    ]
    if client.ca_cert:
        lines.append(f"export VAULT_CACERT={shlex.quote(client.ca_cert)}")
    if client.namespace:
        lines.append(f"export VAULT_NAMESPACE={shlex.quote(client.namespace)}")
    lines.append(f"export VAULT_TOKEN={shlex.quote(token)}")
    atomic_write_text(acl_file, "\n".join(lines) + "\n", mode=0o600)
    target_user = os.environ.get("SUDO_USER") or pwd.getpwuid(os.getuid()).pw_name
    if os.geteuid() == 0 and target_user != "root":
        try:
            info = pwd.getpwnam(target_user)
            os.chown(acl_file, info.pw_uid, info.pw_gid)
        except Exception:
            pass
    log_success(f"Vault ACL env saved to {acl_file}")


def remove_acl_env_file() -> None:
    acl_file = target_acl_file()
    if not acl_file.is_file():
        return
    with acl_file.open("r", encoding="utf-8") as handle:
        first = handle.readline().rstrip("\n")
    if first != ACL_ENV_MARKER:
        log_warn(f"Preserving unmanaged Vault ACL env file: {acl_file}")
        return
    acl_file.unlink()
    log_success(f"Removed Vault ACL env file: {acl_file}")


def create_install_tmpdir(prefix: str) -> Path:
    parent = Path(os.environ.get("TMPDIR", "/var/tmp"))
    if not parent.is_dir() or not os.access(parent, os.W_OK):
        raise CLIError(f"Temporary directory parent is not writable: {parent}. Set TMPDIR to a writable directory with enough space")
    path = Path(tempfile.mkdtemp(prefix=f"{prefix}.", dir=str(parent)))
    log_info(f"Using install temporary directory: {path}")
    return path


def verify_checksum(zip_file: Path, sums_file: Path) -> None:
    expected = ""
    for raw in sums_file.read_text(encoding="utf-8").splitlines():
        parts = raw.split()
        if len(parts) >= 2 and parts[1] == zip_file.name:
            expected = parts[0]
            break
    if not expected:
        raise CLIError(f"Checksum entry not found for {zip_file.name}")
    if expected != sha256_file(zip_file):
        raise CLIError(f"Checksum mismatch for {zip_file.name}")
    log_success(f"Checksum verified: {zip_file.name}")


def download_vault(version: str, arch: str, tmpdir: Path) -> None:
    zip_name = f"vault_{version}_linux_{arch}.zip"
    sums_name = f"vault_{version}_SHA256SUMS"
    base_url = f"https://releases.hashicorp.com/vault/{version}"
    zip_file = tmpdir / zip_name
    sums_file = tmpdir / sums_name
    log_info(f"Downloading Vault {version} for linux_{arch}")
    download_file(f"{base_url}/{zip_name}", zip_file, timeout=300)
    download_file(f"{base_url}/{sums_name}", sums_file, timeout=300)
    verify_checksum(zip_file, sums_file)
    extract_dir = tmpdir / "extract"
    extract_dir.mkdir(parents=True, exist_ok=True)
    extract_zip(zip_file, extract_dir)
    if not (extract_dir / "vault").is_file():
        raise CLIError("Vault binary not found in archive")


def ensure_vault_user() -> None:
    if run(["getent", "group", VAULT_GROUP], check=False, capture=True).returncode != 0:
        log_info(f"Creating system group: {VAULT_GROUP}")
        run_root(["groupadd", "--system", VAULT_GROUP])
    if run(["id", VAULT_USER], check=False, capture=True).returncode == 0:
        return
    shell_path = "/usr/sbin/nologin" if os.access("/usr/sbin/nologin", os.X_OK) else "/bin/false"
    log_info(f"Creating system user: {VAULT_USER}")
    run_root(["useradd", "--system", "--gid", VAULT_GROUP, "--home", str(STATE_DIR), "--shell", shell_path, VAULT_USER])


def install_directories() -> None:
    log_info("Creating Vault directories")
    for path, mode, owner, group in [
        (VAULT_ROOT_DIR, "0755", "root", "root"),
        (BIN_DIR, "0755", "root", "root"),
        (VAULT_ROOT_DIR / "etc", "0755", "root", "root"),
        (VAULT_ROOT_DIR / "data", "0755", "root", "root"),
        (VAULT_ROOT_DIR / "lib", "0755", "root", "root"),
        (VAULT_ROOT_DIR / "log", "0750", "root", "root"),
        (CONFIG_DIR, "0755", "root", "root"),
        (TLS_DIR, "0755", "root", "root"),
        (STATE_DIR, "0750", VAULT_USER, VAULT_GROUP),
        (DATA_DIR, "0750", VAULT_USER, VAULT_GROUP),
        (INIT_DIR, "0700", "root", "root"),
    ]:
        if path.exists() and not path.is_dir():
            raise CLIError(f"Path exists but is not a directory: {path}")
        run_root(["install", "-d", "-m", mode, "-o", owner, "-g", group, str(path)])


def stage_binary(tmpdir: Path, version: str) -> Path:
    """Put one release in place under its version and check it runs.

    The release is checked here, before anything points at it, so a bad archive
    fails while the running binary is still the one in use.
    """
    target = versioned_binary_path(BINARY_VERSION_DIR, "vault", version)
    log_info(f"Installing binary: {target}")
    run_root(["install", "-d", "-m", "0755", "-o", "root", "-g", "root", str(BIN_DIR)])
    run_root(["install", "-d", "-m", "0755", "-o", "root", "-g", "root", str(BINARY_VERSION_DIR)])
    run_root(["install", "-m", "0755", "-o", "root", "-g", "root", str(tmpdir / "extract" / "vault"), str(target)])
    reported = parse_binary_version(run([str(target), "version"], capture=True, check=False).stdout or "")
    if reported != version:
        raise CLIError(f"Installed binary reports version {reported or 'unknown'}, expected {version}")
    return target


def install_binary(tmpdir: Path, version: str) -> None:
    target = stage_binary(tmpdir, version)
    atomic_symlink(target, BIN_PATH)
    run_root(["install", "-d", "-m", "0755", "-o", "root", "-g", "root", str(BIN_ENTRY.parent)])
    run_root(["ln", "-sfn", str(BIN_PATH), str(BIN_ENTRY)])
    log_success(f"Vault binary entry installed: {BIN_ENTRY}")
    run([str(BIN_PATH), "version"])


TLS_VALUE_PATTERN = re.compile(r"^[A-Za-z0-9._:*-]+$")


def validate_tls_value(label: str, value: str) -> str:
    if not TLS_VALUE_PATTERN.match(value):
        raise CLIError(f"Invalid {label}: {value}")
    return value


def looks_like_ip_address(value: str) -> bool:
    return bool(re.match(r"^[0-9]+(\.[0-9]+){3}$", value)) or ":" in value


def url_host(url: str) -> str:
    host = re.sub(r"^[a-zA-Z][a-zA-Z0-9+.-]*://", "", url).split("/")[0]
    if host.startswith("["):
        return host[1:host.index("]")] if "]" in host else host
    return host.rsplit(":", 1)[0] if host.count(":") == 1 else host


def default_tls_sans(dns_names: list[str], ip_addresses: list[str], addresses: list[str]) -> tuple[list[str], list[str]]:
    """Always cover localhost plus whatever hosts the configured addresses name."""
    dns = list(dns_names)
    ips = list(ip_addresses)
    for value in ["localhost", *(url_host(address) for address in addresses if address)]:
        if not value:
            continue
        target = ips if looks_like_ip_address(value) else dns
        if value not in target:
            target.append(value)
    for value in ["127.0.0.1", "::1"]:
        if value not in ips:
            ips.append(value)
    return dns, ips


def openssl_alt_names(dns_names: list[str], ip_addresses: list[str]) -> str:
    lines = [f"DNS.{index} = {value}" for index, value in enumerate(dns_names, start=1)]
    lines.extend(f"IP.{index} = {value}" for index, value in enumerate(ip_addresses, start=1))
    return "\n".join(lines)


def install_self_signed_tls_cert(tmpdir: Path, common_name: str, dns_names: list[str], ip_addresses: list[str]) -> None:
    validate_tls_value("TLS common name", common_name)
    require_command("openssl")
    tls_tmp = tmpdir / "tls"
    tls_tmp.mkdir(mode=0o700, parents=True, exist_ok=True)
    alt_names = openssl_alt_names(dns_names, ip_addresses)
    (tls_tmp / "ca.conf").write_text(
        "[req]\ndistinguished_name = dn\nx509_extensions = v3_ca\nprompt = no\n\n"
        "[dn]\nC = CN\nST = HongKong\nL = HongKong\nO = Vault\nOU = Vault CA\nCN = vault-root-ca\n\n"
        "[v3_ca]\nsubjectKeyIdentifier = hash\nauthorityKeyIdentifier = keyid:always,issuer\n"
        "basicConstraints = critical, CA:true\nkeyUsage = critical, keyCertSign, cRLSign\n",
        encoding="utf-8",
    )
    (tls_tmp / "server.conf").write_text(
        "[req]\ndistinguished_name = dn\nreq_extensions = v3_req\nprompt = no\n\n"
        f"[dn]\nC = CN\nST = HongKong\nL = HongKong\nO = Vault\nOU = Vault\nCN = {common_name}\n\n"
        "[v3_req]\nbasicConstraints = CA:false\nkeyUsage = critical, digitalSignature, keyEncipherment\n"
        "extendedKeyUsage = serverAuth\nsubjectAltName = @alt_names\n\n"
        f"[alt_names]\n{alt_names}\n",
        encoding="utf-8",
    )
    (tls_tmp / "server-ext.conf").write_text(
        "authorityKeyIdentifier = keyid,issuer\nbasicConstraints = CA:false\n"
        "keyUsage = critical, digitalSignature, keyEncipherment\nextendedKeyUsage = serverAuth\n"
        "subjectAltName = @alt_names\n\n"
        f"[alt_names]\n{alt_names}\n",
        encoding="utf-8",
    )
    log_info("Generating self-signed Vault TLS certificate")
    quiet = {"capture": True}
    run(["openssl", "genrsa", "-out", str(tls_tmp / "ca.key"), "4096"], **quiet)
    run(["openssl", "req", "-x509", "-new", "-nodes", "-key", str(tls_tmp / "ca.key"), "-days", "3650",
         "-out", str(tls_tmp / "ca.crt"), "-config", str(tls_tmp / "ca.conf"), "-extensions", "v3_ca"], **quiet)
    run(["openssl", "genrsa", "-out", str(tls_tmp / "server.key"), "4096"], **quiet)
    run(["openssl", "req", "-new", "-key", str(tls_tmp / "server.key"), "-out", str(tls_tmp / "server.csr"),
         "-config", str(tls_tmp / "server.conf")], **quiet)
    run(["openssl", "x509", "-req", "-in", str(tls_tmp / "server.csr"), "-CA", str(tls_tmp / "ca.crt"),
         "-CAkey", str(tls_tmp / "ca.key"), "-CAcreateserial", "-out", str(tls_tmp / "server.crt"),
         "-days", "3650", "-extfile", str(tls_tmp / "server-ext.conf")], **quiet)
    run_root(["install", "-d", "-m", "0755", "-o", "root", "-g", "root", str(TLS_DIR)])
    run_root(["install", "-m", "0600", "-o", "root", "-g", "root", str(tls_tmp / "ca.key"), str(TLS_DIR / "ca.key")])
    run_root(["install", "-m", "0644", "-o", "root", "-g", "root", str(tls_tmp / "ca.crt"), str(TLS_CA_CERT_FILE)])
    run_root(["install", "-m", "0644", "-o", "root", "-g", "root", str(tls_tmp / "server.crt"), str(TLS_CERT_FILE)])
    run_root(["install", "-m", "0640", "-o", "root", "-g", VAULT_GROUP, str(tls_tmp / "server.key"), str(TLS_KEY_FILE)])
    log_success(f"Vault TLS certificate installed: {TLS_CERT_FILE}")


def node_id() -> str:
    host = re.sub(r"[^A-Za-z0-9_.-]", "", os.uname().nodename)[:48]
    return f"vault-{host}" if host else "vault-node"


def write_vault_config(settings: argparse.Namespace) -> None:
    ensure_managed_or_absent(CONFIG_FILE)
    lines = [
        MANAGED_MARKER,
        "ui = true",
        "disable_mlock = true",
        f"api_addr = {hcl_string(settings.api_addr)}",
        f"cluster_addr = {hcl_string(settings.cluster_addr)}",
        "",
        'storage "raft" {',
        f"  path    = {hcl_string(str(DATA_DIR))}",
        f"  node_id = {hcl_string(node_id())}",
        "}",
        "",
        'listener "tcp" {',
        f"  address         = {hcl_string(settings.listen_address)}",
        f"  cluster_address = {hcl_string(settings.cluster_address)}",
        f"  tls_disable     = {settings.tls_disable}",
    ]
    if settings.tls_cert_file:
        lines.append(f"  tls_cert_file   = {hcl_string(settings.tls_cert_file)}")
    if settings.tls_key_file:
        lines.append(f"  tls_key_file    = {hcl_string(settings.tls_key_file)}")
    lines.append("}")
    log_info(f"Installing Vault config: {CONFIG_FILE}")
    install_text(CONFIG_FILE, "\n".join(lines) + "\n", mode="0640", owner="root", group=VAULT_GROUP)


def write_client_env(api_addr: str, ca_cert_file: str) -> None:
    lines = [f"VAULT_ADDR={api_addr}"]
    if ca_cert_file:
        lines.append(f"VAULT_CACERT={ca_cert_file}")
    log_info(f"Installing Vault client defaults: {CLIENT_ENV_FILE}")
    install_text(CLIENT_ENV_FILE, "\n".join(lines) + "\n", mode="0644", owner="root", group="root")


def write_systemd_service() -> None:
    content = f"""[Unit]
Description=Vault
Documentation=https://developer.hashicorp.com/vault/docs
Wants=network-online.target
After=network-online.target

[Service]
User={VAULT_USER}
Group={VAULT_GROUP}
ExecReload=/bin/kill -HUP $MAINPID
ExecStart={BIN_PATH} server -config={CONFIG_FILE}
KillSignal=SIGINT
LimitNOFILE=65536
Restart=on-failure
RestartSec=2
TimeoutStopSec=30
NoNewPrivileges=yes
PrivateTmp=yes
ProtectSystem=full
ProtectHome=read-only
ReadWritePaths={STATE_DIR}

[Install]
WantedBy=multi-user.target
"""
    log_info(f"Installing systemd service: {SYSTEMD_SERVICE}")
    install_text(SYSTEMD_SERVICE, content, mode="0644")


def wait_for_vault_api(client: VaultClient) -> None:
    url = client.health_url()
    log_info("Waiting for Vault HTTP API")
    for _ in range(60):
        if http_status(url, cafile=client.ca_cert) in {200, 429, 472, 473, 501, 503}:
            return
        if command_exists("systemctl") and run_root(["systemctl", "is-active", "--quiet", "vault"], check=False).returncode != 0:
            log_error("Vault service is not active")
            if command_exists("journalctl"):
                run_root(["journalctl", "-u", "vault", "-n", "80", "--no-pager"], check=False)
            raise CLIError("Vault service failed to start")
        time.sleep(2)
    if command_exists("journalctl"):
        run_root(["journalctl", "-u", "vault", "-n", "80", "--no-pager"], check=False)
    raise CLIError(f"Timed out waiting for Vault HTTP API: {url}")


def write_tool_manifest() -> None:
    lines: list[str] = []
    for name in ("vault-manager", "VERSION"):
        path = TOOL_DIR / name
        if path.is_file():
            lines.append(f"{sha256_file(path)}  {name}")
    install_text(TOOL_MANIFEST_FILE, "\n".join(lines) + "\n", mode="0644")


def source_tool_revision(script_dir: Path) -> tuple[str, bool]:
    """The git revision of the source tree the snapshot is taken from.

    Returns ("unknown", False) when git is unavailable or the source is not a
    checkout. Dirtiness is scoped to the tool directory, so unrelated edits
    elsewhere in the repository do not mark the snapshot as modified.
    """
    if not command_exists("git"):
        return "unknown", False
    revision = run(["git", "-C", str(script_dir), "rev-parse", "--short", "HEAD"],
                   capture=True, check=False)
    if revision.returncode != 0:
        return "unknown", False
    # the pathspec is resolved relative to -C, so it must be "." and not script_dir
    status = run(["git", "-C", str(script_dir), "status", "--porcelain", "--", "."],
                 capture=True, check=False)
    dirty = status.returncode == 0 and bool((status.stdout or "").strip())
    return (revision.stdout or "").strip() or "unknown", dirty


def read_installed_tool_revision() -> str:
    metadata = read_install_metadata()
    revision = metadata.get("tool_revision")
    if isinstance(revision, str) and revision.strip():
        return revision.strip() + ("-dirty" if metadata.get("tool_revision_dirty") else "")
    values: dict[str, str] = {}
    try:
        for line in TOOL_VERSION_FILE.read_text(encoding="utf-8").splitlines():
            key, sep, value = line.partition("=")
            if sep:
                values[key] = value.strip()
    except OSError:
        return "unknown"
    revision = values.get("tool_revision", "")
    if not revision:
        return "unknown"
    return revision + ("-dirty" if values.get("tool_revision_dirty") == "true" else "")


def write_install_metadata(version: str, revision: str = "unknown", dirty: bool = False) -> None:
    metadata = {
        "tool": "vault-manager",
        "root_dir": str(VAULT_ROOT_DIR),
        "tool_dir": str(TOOL_DIR),
        "manager_path": str(TOOL_PATH),
        "manager_entry": str(TOOL_ENTRY),
        "vault_binary": str(BIN_PATH),
        "vault_entry": str(BIN_ENTRY),
        "config_file": str(CONFIG_FILE),
        "client_env_file": str(CLIENT_ENV_FILE),
        "tls_dir": str(TLS_DIR),
        "data_dir": str(DATA_DIR),
        "state_dir": str(STATE_DIR),
        "init_dir": str(INIT_DIR),
        "service": str(SYSTEMD_SERVICE),
        "vault_version": version,
        "installed_at": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
        "tool_revision": revision,
        "tool_revision_dirty": dirty,
        "manifest_file": str(TOOL_MANIFEST_FILE),
        "manifest_sha256": sha256_file(TOOL_MANIFEST_FILE) if TOOL_MANIFEST_FILE.is_file() else "",
        "audit_log": str(AUDIT_LOG_FILE),
    }
    run_root(["install", "-d", "-m", "0750", "-o", "root", "-g", "root", str(TOOL_STATE_DIR)])
    install_text(INSTALL_METADATA_FILE, json.dumps(metadata, indent=2, sort_keys=True) + "\n", mode="0644")


def write_state_pointer() -> None:
    content = "\n".join(
        [
            "Managed by vault-manager",
            f"Install metadata: {INSTALL_METADATA_FILE}",
            f"Tool dir: {TOOL_DIR}",
            f"Config file: {CONFIG_FILE}",
            f"Audit log: {AUDIT_LOG_FILE}",
            "",
        ]
    )
    install_text(STATE_POINTER_FILE, content, mode="0644")


def running_from_installed_copy(script_dir: Path) -> bool:
    """True when the running script is the copy that install placed under TOOL_DIR.

    Updating from there would copy the directory onto itself and change nothing.
    """
    try:
        resolved = Path(script_dir).resolve()
        tool_dir = TOOL_DIR.resolve()
    except OSError:
        return False
    return resolved == tool_dir or tool_dir in resolved.parents


def require_tool_source(script_dir: Path) -> None:
    missing: list[str] = []
    if not (script_dir / "vault-manager").is_file():
        missing.append(str(script_dir / "vault-manager"))
    if not (script_dir / "vault_tools").is_dir():
        missing.append(str(script_dir / "vault_tools"))
    if missing:
        raise CLIError(f"Tool source is incomplete: {', '.join(missing)}")


def install_tool_snapshot(version: str, script_dir: Path) -> None:
    revision, dirty = source_tool_revision(script_dir)
    log_info(f"Installing Vault init tools snapshot: {TOOL_DIR} (source revision {revision}{'-dirty' if dirty else ''})")
    run_root(["install", "-d", "-m", "0755", "-o", "root", "-g", "root", str(BIN_DIR)])
    run_root(["install", "-d", "-m", "0755", "-o", "root", "-g", "root", str(TOOL_DIR)])
    safe_remove_path(TOOL_DIR / "manager.sh")
    run_root(["install", "-m", "0755", "-o", "root", "-g", "root", str(script_dir / "vault-manager"), str(TOOL_DIR / "vault-manager")])
    safe_remove_path(TOOL_DIR / "vault_tools")
    run_root(["cp", "-R", str(script_dir / "vault_tools"), str(TOOL_DIR / "vault_tools")])
    run_root(["chown", "-R", "root:root", str(TOOL_DIR / "vault_tools")])
    install_text(
        TOOL_VERSION_FILE,
        f"tool=vault-manager\nvault_version={version}\ntool_revision={revision}\n"
        f"tool_revision_dirty={str(dirty).lower()}\n"
        f"installed_at={time.strftime('%Y-%m-%dT%H:%M:%S%z')}\nsource_dir={script_dir}\n",
        mode="0644",
    )
    write_tool_manifest()
    write_install_metadata(version, revision, dirty)
    run_root(["ln", "-sfn", str(TOOL_DIR / "vault-manager"), str(TOOL_PATH)])
    run_root(["install", "-d", "-m", "0755", "-o", "root", "-g", "root", str(TOOL_ENTRY.parent)])
    run_root(["ln", "-sfn", str(TOOL_PATH), str(TOOL_ENTRY)])
    if LEGACY_TOOL_ENTRY.is_symlink():
        safe_remove_path(LEGACY_TOOL_ENTRY)
    log_success(f"Vault manager entry installed: {TOOL_ENTRY}")


def cmd_tools_update(args: argparse.Namespace) -> int:
    require_linux()
    require_command("install")
    script_dir = current_script_dir(__file__).parent
    if running_from_installed_copy(script_dir):
        raise CLIError(
            f"Refusing to update from the installed copy at {TOOL_DIR}: it would copy onto itself "
            f"and change nothing. Run tools update from a source checkout instead"
        )
    require_tool_source(script_dir)
    version = normalize_version(args.vault_version) if args.vault_version else read_installed_vault_version()
    if version == "unknown":
        log_warn("Installed Vault version metadata not found; recording unknown")
    log_info(f"Updating Vault init tool files from: {script_dir}")
    install_tool_snapshot(version, script_dir)
    log_success("Vault init tools updated")
    return 0


def resolve_install_tls(args: argparse.Namespace) -> argparse.Namespace:
    """Turn the TLS flags into the concrete settings write_vault_config needs."""
    custom_set = bool(args.tls_cert_file or args.tls_key_file or args.tls_ca_cert_file)
    auto_options_set = bool(args.tls_dns or args.tls_ip or args.tls_common_name != "vault-server")
    if args.no_tls and (args.tls_auto or custom_set or auto_options_set):
        raise CLIError("--no-tls cannot be used with TLS options")
    if args.tls_auto and custom_set:
        raise CLIError("--tls-auto cannot be used with custom TLS certificate options")
    if auto_options_set and not args.tls_auto:
        raise CLIError("--tls-dns, --tls-ip and --tls-common-name require --tls-auto")

    mode = "auto" if args.tls_auto else ("custom" if custom_set else "disabled")
    api_addr = args.api_addr or DEFAULT_VAULT_ADDR
    cluster_addr = args.cluster_addr or DEFAULT_CLUSTER_ADDR
    if mode != "disabled":
        api_addr = args.api_addr or "https://127.0.0.1:8200"
        cluster_addr = args.cluster_addr or "https://127.0.0.1:8201"
        if not api_addr.startswith("https://"):
            raise CLIError("TLS is enabled; --api-addr must use https://")
        if not cluster_addr.startswith("https://"):
            raise CLIError("TLS is enabled; --cluster-addr must use https://")
        if mode == "custom" and not (args.tls_cert_file and args.tls_key_file):
            raise CLIError("TLS custom certificate requires both --tls-cert-file and --tls-key-file")
        for label, value in (("certificate", args.tls_cert_file), ("key", args.tls_key_file),
                             ("CA certificate", args.tls_ca_cert_file)):
            if value and not Path(value).is_file():
                raise CLIError(f"TLS {label} file not found: {value}")
    for value in args.tls_dns:
        validate_tls_value("TLS DNS name", value)
    for value in args.tls_ip:
        validate_tls_value("TLS IP address", value)
    return argparse.Namespace(
        mode=mode,
        api_addr=api_addr,
        cluster_addr=cluster_addr,
        listen_address=args.listen_address,
        cluster_address=args.cluster_address,
        tls_disable="false" if mode != "disabled" else "true",
        tls_cert_file=args.tls_cert_file,
        tls_key_file=args.tls_key_file,
        tls_ca_cert_file=args.tls_ca_cert_file,
        tls_common_name=args.tls_common_name,
        tls_dns=list(args.tls_dns),
        tls_ip=list(args.tls_ip),
    )


def cmd_install(args: argparse.Namespace) -> int:
    require_linux()
    for command in ("install", "systemctl", "useradd", "groupadd", "getent"):
        require_command(command)
    settings = resolve_install_tls(args)
    version = resolve_version(args.version)
    arch = detect_arch()
    tmpdir = create_install_tmpdir("vault-install")
    try:
        download_vault(version, arch, tmpdir)
        install_binary(tmpdir, version)
        ensure_vault_user()
        install_directories()
        if settings.mode == "auto":
            dns_names, ip_addresses = default_tls_sans(
                settings.tls_dns, settings.tls_ip, [settings.api_addr, settings.cluster_addr]
            )
            install_self_signed_tls_cert(tmpdir, settings.tls_common_name, dns_names, ip_addresses)
            settings.tls_cert_file = str(TLS_CERT_FILE)
            settings.tls_key_file = str(TLS_KEY_FILE)
            settings.tls_ca_cert_file = str(TLS_CA_CERT_FILE)
        write_vault_config(settings)
        write_client_env(settings.api_addr, settings.tls_ca_cert_file)
        write_systemd_service()
        script_dir = current_script_dir(__file__).parent
        if running_from_installed_copy(script_dir):
            log_warn(f"Running the copy installed at {TOOL_DIR}; the tool files will not change")
            log_warn("Run install from a source checkout to update vault-manager as well")
        install_tool_snapshot(version, script_dir)
        write_state_pointer()
        log_info("Enabling Vault service")
        run_root(["systemctl", "daemon-reload"])
        run_root(["systemctl", "enable", "vault"])
        run_root(["systemctl", "restart", "vault"])
        wait_for_vault_api(VaultClient(argparse.Namespace(addr=settings.api_addr, ca_cert=settings.tls_ca_cert_file)))
    finally:
        shutil.rmtree(tmpdir, ignore_errors=True)
    log_success("Vault installation completed")
    print_install_next_steps()
    return 0


def restart_vault_service(client: VaultClient) -> None:
    run_root(["systemctl", "restart", "vault"])
    time.sleep(2)
    if run_root(["systemctl", "is-active", "--quiet", "vault"], check=False).returncode != 0:
        if command_exists("journalctl"):
            run_root(["journalctl", "-u", "vault", "-n", "80", "--no-pager"], check=False)
        raise CLIError("Vault service failed to start")
    wait_for_vault_api(client)


def read_install_metadata_as_root() -> dict[str, Any]:
    """install.json sits in a root-only directory, so a sudoer can only read it through sudo."""
    result = run_root(["cat", str(INSTALL_METADATA_FILE)], capture=True, check=False)
    if result.returncode != 0:
        return {}
    try:
        data = json.loads(result.stdout or "")
    except json.JSONDecodeError:
        return {}
    return data if isinstance(data, dict) else {}


def record_tool_version_file(version: str) -> None:
    """doctor and status fall back to this file when install.json cannot be read."""
    key = "vault_version="
    try:
        lines = TOOL_VERSION_FILE.read_text(encoding="utf-8").splitlines()
    except OSError:
        return
    if not any(line.startswith(key) for line in lines):
        return
    install_text(
        TOOL_VERSION_FILE,
        "\n".join(f"{key}{version}" if line.startswith(key) else line for line in lines) + "\n",
        mode="0644",
    )


def record_upgrade_metadata(previous: str, version: str) -> None:
    """Move the recorded version forward without rewriting the whole install record."""
    metadata = read_install_metadata() or read_install_metadata_as_root()
    if not metadata:
        log_warn(f"Install metadata not readable: {INSTALL_METADATA_FILE}; the recorded version was not updated")
        return
    metadata["vault_version"] = version
    metadata["previous_vault_version"] = previous
    metadata["upgraded_at"] = time.strftime("%Y-%m-%dT%H:%M:%S%z")
    run_root(["install", "-d", "-m", "0750", "-o", "root", "-g", "root", str(TOOL_STATE_DIR)])
    install_text(INSTALL_METADATA_FILE, json.dumps(metadata, indent=2, sort_keys=True) + "\n", mode="0644")
    record_tool_version_file(version)


def upgrade_plan_lines(current: str, target: str, keep: int) -> list[str]:
    lines = [
        "Vault upgrade plan:",
        f"  Current version:  {current}",
        f"  Target version:   {target}",
        f"  Download:         https://releases.hashicorp.com/vault/{target}/vault_{target}_linux_{detect_arch()}.zip",
        f"  Install release:  {versioned_binary_path(BINARY_VERSION_DIR, 'vault', target)}",
        f"  Switch symlink:   {BIN_PATH}",
        "  Restart service:  vault.service",
        f"  Keep releases:    {keep} (older ones are removed once the new one is running)",
        "  Left untouched:   config, TLS material, the raft store, the init output and the tool files",
        "",
        "  Restarting Vault seals it. Every secret stays unreachable until the node is",
        f"  unsealed again, so have the unseal keys at hand ({DEFAULT_INIT_FILE} by",
        "  default). A restart that fails is rolled back to the current release.",
    ]
    if version_tuple(target) < version_tuple(current):
        lines.extend([
            "",
            f"  Downgrade: {current} may have written storage state that {target} cannot read.",
            "  Vault does not support downgrades; restoring the binary may not be enough.",
        ])
    return lines


def warn_on_version_span(current: str, target: str) -> None:
    """Vault supports one minor version at a time; larger jumps are the user's call."""
    cur = version_tuple(current)
    tgt = version_tuple(target)
    if tgt[0] != cur[0]:
        log_warn(f"Major version change {current} -> {target}; read the upgrade guide first")
    elif tgt[1] - cur[1] > 1:
        log_warn(f"{current} -> {target} skips {tgt[1] - cur[1] - 1} minor release(s); "
                 "Vault expects one minor version at a time")


def confirm_upgrade(assume_yes: bool) -> None:
    if assume_yes:
        return
    try:
        answer = input("Proceed with the upgrade? Type yes to continue: ")
    except EOFError as exc:
        raise CLIError("Upgrade requires confirmation. Re-run with --yes for non-interactive use") from exc
    if answer != "yes":
        raise CLIError("Upgrade cancelled")


def cmd_upgrade(args: argparse.Namespace) -> int:
    require_linux()
    for command in ("install", "systemctl"):
        require_command(command)
    if args.keep < 1:
        raise CLIError("--keep must be at least 1")
    if not BIN_PATH.exists():
        raise CLIError(f"Vault is not installed at {BIN_PATH}; run {VAULT_MANAGER_CMD} install first")
    current = installed_binary_version() or read_installed_vault_version()
    if not current or current == "unknown":
        raise CLIError(f"Cannot determine the installed Vault version from {BIN_PATH}")
    target = resolve_upgrade_target(args.version)
    if target == current:
        log_success(f"Vault {current} is already installed; nothing to upgrade")
        recorded = read_installed_vault_version()
        if recorded != current:
            # doctor sends the operator here when the two disagree, so settle it instead of only reporting it
            log_info(f"Recording the installed version over {recorded}")
            record_upgrade_metadata(recorded, current)
        return 0
    if version_tuple(target) < version_tuple(current) and not args.allow_downgrade:
        raise CLIError(f"Refusing to downgrade Vault {current} to {target}; re-run with --allow-downgrade")
    print("\n".join(upgrade_plan_lines(current, target, args.keep)))
    warn_on_version_span(current, target)
    if args.dry_run:
        return 0
    confirm_upgrade(args.yes)
    client = VaultClient(args)
    arch = detect_arch()
    previous = linked_binary_path(BIN_PATH)
    if previous is None:
        log_info(f"Moving the installed binary into {BINARY_VERSION_DIR}")
        previous = adopt_versioned_binary_layout(BIN_PATH, BINARY_VERSION_DIR, "vault", current)
    tmpdir = create_install_tmpdir("vault-upgrade")
    try:
        download_vault(target, arch, tmpdir)
        staged = stage_binary(tmpdir, target)
        log_info(f"Switching {BIN_PATH} to {staged.name}")
        atomic_symlink(staged, BIN_PATH)
        try:
            log_info("Restarting Vault on the new binary")
            restart_vault_service(client)
        except (CLIError, subprocess.CalledProcessError) as exc:
            log_error(f"Vault did not come back on {target}: {exc}")
            log_warn(f"Rolling back to {previous.name}")
            atomic_symlink(previous, BIN_PATH)
            try:
                restart_vault_service(client)
            except (CLIError, subprocess.CalledProcessError) as rollback_error:
                raise CLIError(f"Upgrade to {target} failed and the rollback to {current} also failed: "
                               f"{rollback_error}") from exc
            raise CLIError(f"Upgrade to {target} failed and was rolled back to {current}") from exc
    finally:
        shutil.rmtree(tmpdir, ignore_errors=True)
    record_upgrade_metadata(current, target)
    for removed in prune_binary_versions(BINARY_VERSION_DIR, "vault", keep=args.keep, current=staged):
        log_info(f"Removed old release: {removed}")
    log_success(f"Vault upgraded: {current} -> {target}")
    print("\nVault is sealed after the restart. Next steps:")
    print(f"  1. {VAULT_MANAGER_CMD} unseal --keys-file {DEFAULT_INIT_FILE}")
    print(f"  2. {VAULT_MANAGER_CMD} doctor")
    return 0


def print_install_next_steps() -> None:
    print("\nNext steps:")
    print(f"  1. {VAULT_MANAGER_CMD} init --key-shares 5 --key-threshold 3")
    print(f"  2. {VAULT_MANAGER_CMD} unseal --keys-file {DEFAULT_INIT_FILE}")
    print("  3. source ~/vault.acl")
    print(f"  4. {VAULT_MANAGER_CMD} doctor")


def uninstall_runtime_paths() -> list[Path]:
    return [SYSTEMD_SERVICE, BIN_ENTRY, BIN_PATH, BINARY_VERSION_DIR, CONFIG_DIR]


def uninstall_tool_paths() -> list[Path]:
    return [TOOL_ENTRY, LEGACY_TOOL_ENTRY, TOOL_PATH, TOOL_DIR]


def print_uninstall_plan(args: argparse.Namespace) -> None:
    print("Vault uninstall plan:")
    print("  Stop and disable service:")
    print("    - vault.service")
    print("  Remove runtime paths:")
    for path in uninstall_runtime_paths():
        print(f"    - {path}")
    if args.purge_data or args.purge:
        print("  Remove Vault state and init output:")
        print(f"    - {STATE_DIR}   <-- destroys the raft store; the data is unrecoverable")
        print(f"    - {INIT_DIR}   <-- destroys the unseal keys and root token")
        print("  Remove system user and group:")
        print(f"    - {VAULT_USER} / {VAULT_GROUP}")
    else:
        print("  Preserve Vault state and init output:")
        print(f"    - {STATE_DIR}")
        print(f"    - {INIT_DIR}")
    if args.remove_tools or args.purge:
        print("  Remove tool paths:")
        for path in uninstall_tool_paths():
            print(f"    - {path}")
    else:
        print("  Preserve tool paths:")
        print(f"    - {TOOL_DIR}")
    if args.purge:
        print("  Purge tool state and the generated ACL env file:")
        print(f"    - {TOOL_STATE_DIR}")
        print(f"    - {TOOL_LOG_DIR}")
        print(f"    - {target_acl_file()}")
    else:
        print("  Preserve tool state:")
        print(f"    - {TOOL_STATE_DIR}")
        print(f"    - {TOOL_LOG_DIR}")


def confirm_uninstall(args: argparse.Namespace) -> None:
    if args.yes:
        return
    try:
        answer = input("Proceed with uninstall? Type yes to continue: ")
    except EOFError as exc:
        raise CLIError("Uninstall requires confirmation. Re-run with --yes for non-interactive use") from exc
    if answer != "yes":
        raise CLIError("Uninstall cancelled")


def cmd_uninstall(args: argparse.Namespace) -> int:
    print_uninstall_plan(args)
    if args.dry_run:
        return 0
    confirm_uninstall(args)
    require_linux()
    require_command("systemctl")
    log_info("Stopping Vault service")
    run_root(["systemctl", "stop", "vault"], check=False)
    run_root(["systemctl", "disable", "vault"], check=False)
    log_info("Removing Vault service, binary and config")
    for path in uninstall_runtime_paths():
        if path.exists() or path.is_symlink():
            safe_remove_path(path)
    if args.purge_data or args.purge:
        log_warn(f"Purging Vault state directory: {STATE_DIR}")
        safe_remove_path(STATE_DIR)
        log_warn(f"Purging Vault init directory: {INIT_DIR}")
        safe_remove_path(INIT_DIR)
        if run(["id", VAULT_USER], check=False, capture=True).returncode == 0:
            log_info(f"Removing system user: {VAULT_USER}")
            run_root(["userdel", VAULT_USER], check=False)
        if run(["getent", "group", VAULT_GROUP], check=False, capture=True).returncode == 0:
            log_info(f"Removing system group: {VAULT_GROUP}")
            run_root(["groupdel", VAULT_GROUP], check=False)
    else:
        log_warn(f"Vault state preserved: {STATE_DIR}. Use --purge-data to remove it")
        log_warn(f"Vault init output preserved: {INIT_DIR}. Use --purge-data to remove it")
    if args.remove_tools or args.purge:
        log_info("Removing Vault init tools")
        for path in uninstall_tool_paths():
            if path.exists() or path.is_symlink():
                safe_remove_path(path)
    else:
        log_warn(f"Vault init tools preserved: {TOOL_DIR}. Use --remove-tools to remove them")
    if args.purge:
        remove_acl_env_file()
        log_warn("Purging Vault init tool metadata and audit logs")
        safe_remove_path(TOOL_STATE_DIR)
        safe_remove_path(TOOL_LOG_DIR)
    else:
        log_warn(f"Vault init tool metadata preserved: {TOOL_STATE_DIR}")
        log_warn(f"Vault init tool audit logs preserved: {TOOL_LOG_DIR}")
    run_root(["systemctl", "daemon-reload"])
    run_root(["systemctl", "reset-failed", "vault"], check=False)
    log_success("Vault uninstallation completed")
    return 0


def cmd_init(args: argparse.Namespace) -> int:
    client = VaultClient(args)
    out = Path(args.out) if args.out else DEFAULT_INIT_FILE
    status = client.status_json()
    if status.get("initialized") is True:
        raise CLIError("Vault is already initialized")
    if out.exists() and not args.force:
        raise CLIError(f"Output exists, use --force to overwrite: {out}")
    log_info(f"Initializing Vault: key-shares={args.key_shares} key-threshold={args.key_threshold} out={out}")
    result = client.run(
        ["operator", "init", "-format=json",
         f"-key-shares={args.key_shares}", f"-key-threshold={args.key_threshold}"],
        capture=True,
    )
    payload = result.stdout or ""
    try:
        data = json.loads(payload)
    except json.JSONDecodeError as exc:
        raise CLIError("Vault init did not return JSON; nothing was saved") from exc
    if not data.get("unseal_keys_b64") and not data.get("unseal_keys_hex"):
        raise CLIError("Vault init output contains no unseal keys; refusing to save it")
    # the unseal keys exist only here, so write them before anything else can fail
    handle = tempfile.NamedTemporaryFile("w", encoding="utf-8", delete=False)
    try:
        os.chmod(handle.name, 0o600)
        handle.write(payload)
        handle.close()
        run_root(["install", "-d", "-m", "0700", str(out.parent)])
        run_root(["install", "-m", "0600", handle.name, str(out)])
    finally:
        Path(handle.name).unlink(missing_ok=True)
    log_success(f"Vault init output saved: {out}")
    write_acl_env_file(client, read_token_file(out))
    print("\nNext steps:")
    print(f"  1. {VAULT_MANAGER_CMD} unseal --keys-file {out}")
    print("  2. source ~/vault.acl")
    print(f"  3. {VAULT_MANAGER_CMD} doctor")
    print(f"\nBack up {out} somewhere safe; it holds the only copy of the unseal keys.")
    return 0


def cmd_unseal(args: argparse.Namespace) -> int:
    client = VaultClient(args)
    keys_file = Path(args.keys_file)
    status = client.status_json()
    if status.get("sealed") is False:
        log_success("Vault is already unsealed")
        return 0
    parent = keys_file.parent
    if not parent.is_dir():
        raise CLIError(f"Keys file directory not found or inaccessible: {parent}")
    if not keys_file.exists():
        raise CLIError(f"Keys file not found: {keys_file}")
    keys = unseal_keys_from_file(keys_file)
    if not keys:
        raise CLIError(f"Keys file does not contain unseal keys: {keys_file}")
    for key in keys:
        client.run(["operator", "unseal", key], capture=True)
        if client.status_json().get("sealed") is False:
            log_success("Vault unsealed")
            return 0
    raise CLIError("Vault is still sealed after applying keys")


def auth_type_at_path(client: VaultClient, path: str) -> str:
    result = client.run(["auth", "list", "-format=json"], capture=True, check=False)
    if result.returncode != 0:
        return ""
    try:
        data = json.loads(result.stdout or "{}")
    except json.JSONDecodeError:
        return ""
    key = path.strip("/")
    entry = data.get(f"{key}/", {}) if key else {}
    return entry.get("type", "") if isinstance(entry, dict) else ""


def cmd_auth_list(args: argparse.Namespace) -> int:
    VaultClient(args).run(["auth", "list"])
    return 0


def cmd_auth_enable(args: argparse.Namespace) -> int:
    client = VaultClient(args)
    path = args.path or args.type
    existing = auth_type_at_path(client, path)
    if existing:
        if existing == args.type:
            log_success(f"Auth method already enabled: {path} ({args.type})")
            return 0
        raise CLIError(f"Auth path {path} already exists with type {existing}")
    command = ["auth", "enable", f"-path={path}"]
    if args.description:
        command.append(f"-description={args.description}")
    if args.default_lease_ttl:
        command.append(f"-default-lease-ttl={args.default_lease_ttl}")
    if args.max_lease_ttl:
        command.append(f"-max-lease-ttl={args.max_lease_ttl}")
    command.append(args.type)
    client.run(command)
    return 0


def cmd_auth_disable(args: argparse.Namespace) -> int:
    client = VaultClient(args)
    if not auth_type_at_path(client, args.path):
        log_success(f"Auth method already absent: {args.path}")
        return 0
    client.run(["auth", "disable", args.path])
    return 0


def cmd_auth_read(args: argparse.Namespace) -> int:
    VaultClient(args).run(["read", f"auth/{args.path}"])
    return 0


def cmd_auth_write(args: argparse.Namespace) -> int:
    if not args.pairs:
        raise CLIError("auth write requires KEY=VALUE arguments")
    VaultClient(args).run(["write", f"auth/{args.path}", *args.pairs])
    return 0


def cmd_policy_list(args: argparse.Namespace) -> int:
    VaultClient(args).run(["policy", "list"])
    return 0


def cmd_policy_read(args: argparse.Namespace) -> int:
    VaultClient(args).run(["policy", "read", args.name])
    return 0


def cmd_policy_write(args: argparse.Namespace) -> int:
    if not Path(args.file).is_file():
        raise CLIError(f"Policy file not found: {args.file}")
    VaultClient(args).run(["policy", "write", args.name, args.file])
    return 0


def cmd_policy_delete(args: argparse.Namespace) -> int:
    VaultClient(args).run(["policy", "delete", args.name])
    return 0


SEAL_HINTS = {
    501: ("Vault is not initialized", f"{VAULT_MANAGER_CMD} init --key-shares 5 --key-threshold 3"),
    503: ("Vault is sealed", f"{VAULT_MANAGER_CMD} unseal --keys-file {DEFAULT_INIT_FILE}"),
}


def certificate_expiry(path: Path) -> tuple[str, int | None]:
    """Return (notAfter, days_left). days_left is None when openssl cannot tell us."""
    if not command_exists("openssl") or not path.is_file():
        return "", None
    result = run(["openssl", "x509", "-in", str(path), "-noout", "-enddate"], capture=True, check=False)
    match = re.search(r"notAfter=(.+)", (result.stdout or "").strip())
    if not match:
        return "", None
    not_after = match.group(1).strip()
    for fmt in ("%b %d %H:%M:%S %Y %Z", "%b %d %H:%M:%S %Y"):
        try:
            expiry = time.mktime(time.strptime(not_after.replace(" GMT", ""), fmt.replace(" %Z", "")))
        except ValueError:
            continue
        return not_after, int((expiry - time.time()) // 86400)
    return not_after, None


def doctor_tls(values: dict[str, str]) -> int:
    failures = 0
    tls_disable = values.get("tls_disable", "")
    doctor_info(f"tls_disable  = {unset_label(tls_disable)}")
    if tls_disable != "false":
        doctor_check("WARN", "Listener TLS is disabled; tokens travel in clear text")
        return failures
    for key in ("tls_cert_file", "tls_key_file"):
        value = values.get(key, "")
        if not value:
            doctor_check("FAIL", f"TLS is enabled but {key} is not set")
            failures += 1
            continue
        if Path(value).is_file():
            doctor_check("OK", f"{key} exists: {value}")
        else:
            doctor_check("FAIL", f"{key} missing: {value}; vault.service will not start")
            failures += 1
    cert_file = values.get("tls_cert_file", "")
    if cert_file and Path(cert_file).is_file():
        not_after, days_left = certificate_expiry(Path(cert_file))
        if days_left is None:
            doctor_info(f"certificate expiry = {unset_label(not_after)}")
        elif days_left < 0:
            doctor_check("FAIL", f"Certificate expired {abs(days_left)} days ago: {not_after}")
            failures += 1
        elif days_left <= CERT_EXPIRY_WARN_DAYS:
            doctor_check("WARN", f"Certificate expires in {days_left} days: {not_after}")
        else:
            doctor_check("OK", f"Certificate valid for {days_left} more days")
    return failures


def doctor_init_output() -> int:
    """The init file holds every unseal key and the root token, so its mode matters."""
    if not INIT_DIR.exists():
        doctor_info(f"Init output: {INIT_DIR} does not exist")
        return 0
    failures = 0
    files = sorted(path for path in INIT_DIR.glob("*.json") if path.is_file())
    if not files:
        doctor_info(f"Init output: no JSON files under {INIT_DIR}")
        return 0
    for path in files:
        mode = path.stat().st_mode & 0o777
        owner = path.stat().st_uid
        if mode == 0o600 and owner == 0:
            doctor_check("OK", f"{path.name}: mode 0600, owned by root")
        else:
            doctor_check("FAIL", f"{path.name}: mode {mode:04o}, uid {owner}; unseal keys must be 0600 root-owned")
            failures += 1
    return failures


def doctor_node_runtime() -> int:
    failures = 0
    recorded = read_installed_vault_version()
    doctor_info(f"recorded version = {recorded}")
    doctor_info(f"tool revision    = {read_installed_tool_revision()}")
    actual = installed_binary_version()
    if actual:
        doctor_info(f"binary version   = {actual}")
        if recorded not in {"unknown", actual}:
            doctor_check("WARN", f"Binary version {actual} differs from recorded {recorded}; "
                                 f"run {VAULT_MANAGER_CMD} upgrade to install a known release")
    for path, label, required in ((DATA_DIR, "Raft data directory", True), (TOOL_DIR, "Tool copy", False)):
        if path.is_dir():
            doctor_check("OK", f"{label} exists: {path}")
        elif required:
            doctor_check("FAIL", f"{label} missing: {path}")
            failures += 1
        else:
            doctor_check("WARN", f"{label} missing: {path}; this node was not installed by vault-manager")
    return failures


def doctor_seal_state(client: VaultClient) -> int:
    status = client.status_json()
    if not status:
        doctor_check("WARN", "Cannot read vault status; check the address, TLS and whether the binary is installed")
        return 0
    failures = 0
    initialized = status.get("initialized")
    sealed = status.get("sealed")
    if initialized is True:
        doctor_check("OK", "Vault is initialized")
    else:
        doctor_check("FAIL", f"Vault is not initialized; run {VAULT_MANAGER_CMD} init")
        failures += 1
    if sealed is False:
        doctor_check("OK", "Vault is unsealed")
    elif sealed is True:
        doctor_check("FAIL", f"Vault is sealed; run {VAULT_MANAGER_CMD} unseal --keys-file {DEFAULT_INIT_FILE}")
        failures += 1
    if status.get("t") or status.get("n"):
        doctor_info(f"seal threshold   = {status.get('t', '?')} of {status.get('n', '?')}")
    if status.get("ha_enabled") is not None:
        doctor_info(f"ha_enabled       = {str(status.get('ha_enabled')).lower()}")
    if status.get("version"):
        doctor_info(f"server version   = {status.get('version')}")
    return failures


def cmd_doctor(args: argparse.Namespace) -> int:
    client = VaultClient(args)
    values = config_values()
    failures = 0
    doctor_check("OK" if sys.platform.startswith("linux") else "FAIL", f"platform: {sys.platform}")
    if not sys.platform.startswith("linux"):
        failures += 1
    if command_exists("systemctl"):
        doctor_check("OK", f"systemctl found: {shutil.which('systemctl')}")
        if run(["systemctl", "is-active", "--quiet", "vault"], check=False).returncode == 0:
            doctor_check("OK", "vault.service is active")
        else:
            doctor_check("FAIL", "vault.service is not active")
            failures += 1
    else:
        doctor_check("FAIL", "systemctl not found")
        failures += 1
    if BIN_PATH.is_file():
        doctor_check("OK", f"Vault binary found: {BIN_PATH}")
    else:
        doctor_check("FAIL", f"Vault binary missing: {BIN_PATH}")
        failures += 1
    if CONFIG_FILE.is_file():
        if is_managed_file(CONFIG_FILE):
            doctor_check("OK", f"Vault config managed: {CONFIG_FILE}")
        else:
            doctor_check("FAIL", f"Vault config exists but is not managed: {CONFIG_FILE}")
            failures += 1
    else:
        doctor_check("FAIL", f"Vault config missing: {CONFIG_FILE}")
        failures += 1

    print("\nNode runtime:")
    failures += doctor_node_runtime()

    print("\nConfiguration:")
    if not values:
        doctor_check("FAIL", f"Config not readable: {CONFIG_FILE}")
        failures += 1
    else:
        doctor_info(f"api_addr     = {unset_label(values['api_addr'])}")
        doctor_info(f"cluster_addr = {unset_label(values['cluster_addr'])}")
        doctor_info(f"listener     = {unset_label(values['listen_address'])} "
                    f"(cluster {unset_label(values['cluster_address'])})")
        doctor_info(f"storage      = raft at {unset_label(values['storage_path'])}, node_id {unset_label(values['node_id'])}")
        failures += doctor_tls(values)
    doctor_info(f"client env   = VAULT_ADDR {unset_label(client_env_value('VAULT_ADDR'))}, "
                f"VAULT_CACERT {unset_label(client_env_value('VAULT_CACERT'))}")

    print("\nInit output:")
    failures += doctor_init_output()

    print("\nVault state:")
    url = client.health_url()
    code = http_status(url, cafile=client.ca_cert)
    if code in {200, 429, 472, 473}:
        doctor_check("OK", f"Vault health endpoint reachable: {url} ({code})")
    elif code in SEAL_HINTS:
        reason, fix = SEAL_HINTS[code]
        doctor_check("FAIL", f"{reason} ({code} from {url})")
        doctor_check("INFO", f"Fix: {fix}")
        failures += 1
    else:
        doctor_check("FAIL", f"Vault health endpoint not reachable: {url} ({code})")
        failures += 1
    failures += doctor_seal_state(client)
    if failures == 0:
        print("\nAll checks passed.")
    return 0 if failures == 0 else 1


def status_line(key: str, value: str) -> None:
    print(f"  {key:<22} {value}")


def cmd_status(args: argparse.Namespace) -> int:
    """Show what is configured. doctor answers whether it is healthy."""
    client = VaultClient(args)
    values = config_values()
    print("Install:")
    status_line("recorded version", read_installed_vault_version())
    if BIN_PATH.is_file():
        status_line("binary version", installed_binary_version() or "unknown")
    status_line("binary", str(BIN_PATH) if BIN_PATH.is_file() else "<not installed>")
    linked = linked_binary_path(BIN_PATH)
    if linked:
        status_line("binary release", str(linked))
    kept = [item.name for item in kept_binary_versions(BINARY_VERSION_DIR, "vault")]
    if kept:
        status_line("kept releases", ", ".join(kept))
    status_line("config file", str(CONFIG_FILE))
    status_line("raft data", str(DATA_DIR))
    status_line("init output", str(INIT_DIR))
    status_line("tool dir", str(TOOL_DIR) if TOOL_DIR.is_dir() else "<not installed>")
    status_line("tool revision", read_installed_tool_revision())
    if command_exists("systemctl"):
        status_line("service", (run(["systemctl", "is-active", "vault"], check=False, capture=True).stdout or "").strip() or "unknown")

    print("\nConfiguration:")
    if not values:
        print(f"  <not readable: {CONFIG_FILE}>")
    else:
        status_line("api_addr", unset_label(values["api_addr"]))
        status_line("cluster_addr", unset_label(values["cluster_addr"]))
        status_line("listener", unset_label(values["listen_address"]))
        status_line("tls_disable", unset_label(values["tls_disable"]))
        if values["tls_disable"] == "false":
            status_line("tls_cert_file", unset_label(values["tls_cert_file"]))
        status_line("storage", f"raft at {unset_label(values['storage_path'])}")
        status_line("node_id", unset_label(values["node_id"]))
    status_line("client VAULT_ADDR", unset_label(client_env_value("VAULT_ADDR")))
    status_line("client VAULT_CACERT", unset_label(client_env_value("VAULT_CACERT")))
    status_line("acl env file", str(target_acl_file()) if target_acl_file().is_file() else "<absent>")

    print("\nInit output:")
    files = sorted(INIT_DIR.glob("*.json")) if INIT_DIR.is_dir() else []
    if not files:
        print("  <none>")
    for path in files:
        status_line(path.name, f"mode {path.stat().st_mode & 0o777:04o}")

    print("\nVault status:")
    if BIN_PATH.is_file():
        client.run(["status"], check=False)
    else:
        print(f"  Vault binary not found: {BIN_PATH}; skipping vault status")
    print(f"\nRun '{VAULT_MANAGER_CMD} doctor' to check whether any of this is broken.")
    return 0


def cmd_quickstart(_: argparse.Namespace) -> int:
    print(
        f"""Vault manager quickstart, in the order the commands are meant to be used.

1. Set up the node
     {VAULT_MANAGER_CMD} install --version {DEFAULT_VAULT_VERSION}

   Or with a self-signed certificate, so tokens do not travel in clear text:
     {VAULT_MANAGER_CMD} install --tls-auto

2. Bring Vault online
     {VAULT_MANAGER_CMD} init --key-shares 5 --key-threshold 3
     {VAULT_MANAGER_CMD} unseal --keys-file {DEFAULT_INIT_FILE}
     source {target_acl_file()}

3. Configure Vault
     {VAULT_MANAGER_CMD} auth enable jwt --path jwt-nomad
     {VAULT_MANAGER_CMD} policy write app-read ./policy.hcl

4. Check everything at once
     {VAULT_MANAGER_CMD} status
     {VAULT_MANAGER_CMD} doctor

5. Review before removing anything
     {VAULT_MANAGER_CMD} uninstall --dry-run

Back up {DEFAULT_INIT_FILE}. It holds the only copy of the unseal keys; losing
it means losing the data in the raft store.

Run '{VAULT_MANAGER_CMD} tutor <topic>' for the reasoning behind each step.
"""
    )
    return 0


TUTOR_TOPICS = {
    "overview": f"""Vault manager tutor.

Manage a single-node Vault install, its bootstrap files, and the auth methods
and policies these tools depend on.

Start here:
  {VAULT_MANAGER_CMD} quickstart
  {VAULT_MANAGER_CMD} doctor

Topics, in the same order as the commands:
  1. Set up          install, tls
  2. Bring online    init, unseal
  3. Configure       auth, policy
  4. Remove          uninstall
  5. When it breaks  troubleshoot
""",
    "install": f"""Install a single node.

Downloads the Vault binary, writes the managed config, and starts
vault.service. Vault comes up initialized=false and sealed, which is expected:
'tutor init' is the next step.

There is no separate installer for this tool. install copies vault-manager
into {TOOL_DIR}
and links it onto PATH, so run it from a source checkout the first time.

  ./tools/vault/vault-manager install --version {DEFAULT_VAULT_VERSION}
  {VAULT_MANAGER_CMD} doctor

Layout:
  binary : {BIN_PATH} -> {BIN_ENTRY}
  config : {CONFIG_FILE}
  raft   : {DATA_DIR}
  init   : {INIT_DIR}
  service: {SYSTEMD_SERVICE}
""",
    "tls": f"""Choose how the listener is protected.

Without TLS every token, including the root token, crosses the network in
clear text. That is only acceptable when nothing but this host talks to Vault.

  {VAULT_MANAGER_CMD} install                  # no TLS, the default
  {VAULT_MANAGER_CMD} install --tls-auto       # generate a CA and server certificate
  {VAULT_MANAGER_CMD} install --tls-auto --tls-ip 10.2.37.64 --api-addr https://10.2.37.64:8200

--tls-auto writes a CA and certificate under {TLS_DIR}
and records the CA in
{CLIENT_ENV_FILE},
so later commands verify it without extra flags. The certificate always covers
localhost and 127.0.0.1; add --tls-dns or --tls-ip for the addresses other
hosts use.

To use certificates you already have:
  {VAULT_MANAGER_CMD} install --tls-cert-file ... --tls-key-file ... --tls-ca-cert-file ...

Enabling TLS forces api_addr and cluster_addr to https. doctor reports the
certificate expiry, so a self-signed certificate does not lapse unnoticed.
""",
    "init": f"""Initialize Vault and save the unseal keys.

init generates the unseal keys and the root token. Vault returns them exactly
once, and
{DEFAULT_INIT_FILE}
is the only copy, written 0600 and root-owned. Back it up before you do
anything else. Losing it means losing the raft store.

init also writes {target_acl_file()} so your shell can reach Vault:

  {VAULT_MANAGER_CMD} init --key-shares 5 --key-threshold 3
  source {target_acl_file()}

The default is 5 shares with a threshold of 3: Vault hands back five keys and
any three of them unseal it. Give the five to different people, and no single
person can unseal Vault alone, while losing one or two keys is survivable.

  --key-shares 1 --key-threshold 1

collapses that to a single key. It is quicker for a throwaway lab, but that one
key is then the only thing between anyone who reads the file and every secret,
and losing it loses the raft store.

init refuses to run against an initialized Vault, and refuses to overwrite an
existing output file without --force.
""",
    "unseal": f"""Unseal Vault so it can serve requests.

Vault seals itself on every restart, so this is not a one-off: after a reboot
the API answers 503 until you unseal it again.

  {VAULT_MANAGER_CMD} unseal --keys-file {DEFAULT_INIT_FILE}

The command applies keys from the init JSON one at a time and stops as soon as
Vault reports itself unsealed. It is a no-op when Vault is already unsealed.
""",
    "auth": f"""Manage auth methods.

  {VAULT_MANAGER_CMD} auth list
  {VAULT_MANAGER_CMD} auth enable jwt --path jwt-nomad --description "Nomad workload identity"
  {VAULT_MANAGER_CMD} auth write jwt-nomad/config jwks_url=http://127.0.0.1:4646/.well-known/jwks.json
  {VAULT_MANAGER_CMD} auth read jwt-nomad/config
  {VAULT_MANAGER_CMD} auth disable jwt-nomad

enable is idempotent for the same type at the same path, and fails when the
path exists with a different type. disable is idempotent when the path is
already absent.

KEY=VALUE arguments land in shell history and in this tool's audit log. Do not
pass secrets that way.

For the Nomad workload identity setup specifically, prefer the Nomad side:
  nomad-manager vault jwt apply --profile default
""",
    "policy": f"""Manage policies from local HCL files.

  {VAULT_MANAGER_CMD} policy list
  {VAULT_MANAGER_CMD} policy write app-read ./policy.hcl
  {VAULT_MANAGER_CMD} policy read app-read
  {VAULT_MANAGER_CMD} policy delete app-read

A minimal policy file:
  path "kv/data/app/*" {{
    capabilities = ["read"]
  }}

write is idempotent for identical content. Keep policy files in version
control; Vault stores the text but not its history.
""",
    "uninstall": f"""Remove Vault from this node.

--dry-run prints the plan and changes nothing; always run it first.

  {VAULT_MANAGER_CMD} uninstall --dry-run
  {VAULT_MANAGER_CMD} uninstall

Default uninstall keeps {STATE_DIR}
and {INIT_DIR}, so the data and the unseal keys survive.
--purge-data removes both, which destroys the raft store beyond recovery.
--purge additionally removes the installed tools, metadata, audit logs and
{target_acl_file()}.
""",
    "troubleshoot": f"""Start with the aggregate check, then narrow down.

  {VAULT_MANAGER_CMD} doctor
  {VAULT_MANAGER_CMD} status
  systemctl status vault
  journalctl -u vault -n 100 --no-pager

Reading the health endpoint yourself:
  503 means sealed        -> {VAULT_MANAGER_CMD} unseal --keys-file {DEFAULT_INIT_FILE}
  501 means uninitialized -> {VAULT_MANAGER_CMD} init
  200 means ready

doctor decodes both for you and prints the command to run.

Permission denied on every request usually means no token:
  source {target_acl_file()}

x509 errors against a --tls-auto install mean the CA is not being verified.
{CLIENT_ENV_FILE}
records it, and doctor reports what the client picked up.
""",
}


def cmd_tutor(args: argparse.Namespace) -> int:
    topic = args.topic or "overview"
    if topic not in TUTOR_TOPICS:
        raise CLIError(f"Unknown tutor topic: {topic}. Available: {', '.join(TUTOR_TOPICS)}")
    print(TUTOR_TOPICS[topic])
    return 0


COMMAND_GROUPS: list[tuple[str, str, list[tuple[str, str]]]] = [
    (
        "Set up the node",
        "",
        [
            ("install", "Install Vault and this tool, write config, start the service"),
            ("doctor", "Check the node, the seal state and the init output"),
            ("status", "Show the effective configuration of this node"),
        ],
    ),
    (
        "Bring Vault online",
        "A fresh install is uninitialized and sealed until these two have run.",
        [
            ("init", "Generate the unseal keys and root token, once"),
            ("unseal", "Unseal Vault, needed again after every restart"),
        ],
    ),
    (
        "Configure Vault",
        "",
        [
            ("auth", "Auth methods: list, enable, disable, read, write"),
            ("policy", "Policies from local HCL files"),
        ],
    ),
    (
        "Maintain and remove",
        "",
        [
            ("upgrade", "Install another Vault release and restart the server"),
            ("tools", "Update the installed vault-manager files"),
            ("uninstall", "Remove Vault, after showing a removal plan"),
        ],
    ),
    (
        "Learn",
        "",
        [
            ("quickstart", "A copyable end-to-end setup workflow"),
            ("tutor", "Per-topic guidance with explanations"),
        ],
    ),
]


def grouped_command_names() -> list[str]:
    return [name for _, _, commands in COMMAND_GROUPS for name, _ in commands]


def registered_command_names(parser: argparse.ArgumentParser) -> list[str]:
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            return list(action.choices)
    return []


def command_group_help() -> str:
    """Render the command list grouped by the order the commands are used in."""
    lines: list[str] = []
    for index, (title, note, commands) in enumerate(COMMAND_GROUPS, start=1):
        lines.append(f"{index}. {title}")
        if note:
            lines.append(f"     {note}")
        for name, summary in commands:
            lines.append(f"     {name:<14} {summary}")
        lines.append("")
    return "\n".join(lines).rstrip()


def add_client_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--addr", default="", help=f"Vault address (default: {CLIENT_ENV_FILE} or {DEFAULT_VAULT_ADDR})")
    parser.add_argument("--ca-cert", default="", help="Vault CA certificate file")
    parser.add_argument("--namespace", default="", help="Vault Enterprise namespace")
    parser.add_argument("--token-file", default="", help="Read the token from a plain file or from the init JSON")


def build_parser() -> argparse.ArgumentParser:
    parser = CLIArgumentParser(
        prog=VAULT_MANAGER_CMD,
        description="Manage a single-node Vault install, in the order you actually use it.\n"
        "\n"
        f"{command_group_help()}\n"
        "\n"
        f"Run '{VAULT_MANAGER_CMD} <command> --help' for what a command does and when to use it,\n"
        f"or '{VAULT_MANAGER_CMD} quickstart' for the whole path end to end.",
        epilog=f"""Examples:
  {VAULT_MANAGER_CMD} install --tls-auto
  {VAULT_MANAGER_CMD} init --key-shares 5 --key-threshold 3
  {VAULT_MANAGER_CMD} unseal --keys-file {DEFAULT_INIT_FILE}
  {VAULT_MANAGER_CMD} auth enable jwt --path jwt-nomad
  {VAULT_MANAGER_CMD} policy write app-read ./policy.hcl
  {VAULT_MANAGER_CMD} doctor
  {VAULT_MANAGER_CMD} uninstall --dry-run
""",
    )
    sub = parser.add_subparsers(dest="command", metavar="<command>")
    parser.set_defaults(func=lambda _: missing_subcommand(parser, VAULT_MANAGER_CMD))

    install = sub.add_parser(
        "install",
        description="Install Vault, write the managed config and start vault.service.\n"
        "\n"
        "Vault comes up uninitialized and sealed; that is expected. Run init and unseal next.\n"
        "\n"
        "install also copies this tool itself into the node: vault-manager and the vault_tools\n"
        f"package go to {TOOL_DIR},\n"
        f"linked onto PATH as {TOOL_ENTRY}.\n"
        "Refresh that copy later with 'tools update'.\n"
        "\n"
        "TLS is off by default, which means tokens cross the network in clear text. Use\n"
        "--tls-auto for a generated certificate, or --tls-cert-file/--tls-key-file for your own.",
    )
    install.add_argument("version_pos", nargs="?", help="Vault version, for example 2.0.0 or latest")
    install.add_argument("--version", dest="version_opt", help="Vault version; overrides the positional version")
    install.add_argument("--listen-address", default=DEFAULT_LISTEN_ADDRESS, help=f"Listener address (default: {DEFAULT_LISTEN_ADDRESS})")
    install.add_argument("--cluster-address", default=DEFAULT_CLUSTER_ADDRESS, help=f"Listener cluster address (default: {DEFAULT_CLUSTER_ADDRESS})")
    install.add_argument("--api-addr", default="", help=f"Vault api_addr (default: {DEFAULT_VAULT_ADDR}, or https://127.0.0.1:8200 with TLS)")
    install.add_argument("--cluster-addr", default="", help=f"Vault cluster_addr (default: {DEFAULT_CLUSTER_ADDR}, or https with TLS)")
    install.add_argument("--no-tls", action="store_true", help="Disable listener TLS; this is the default")
    install.add_argument("--tls-auto", action="store_true", help="Generate a CA and server certificate and enable TLS")
    install.add_argument("--tls-cert-file", default="", help="Listener TLS certificate file")
    install.add_argument("--tls-key-file", default="", help="Listener TLS key file")
    install.add_argument("--tls-ca-cert-file", default="", help="CA certificate recorded for client checks")
    install.add_argument("--tls-dns", action="append", default=[], help="Extra DNS SAN for --tls-auto; repeatable")
    install.add_argument("--tls-ip", action="append", default=[], help="Extra IP SAN for --tls-auto; repeatable")
    install.add_argument("--tls-common-name", default="vault-server", help="Certificate common name for --tls-auto (default: vault-server)")
    install.set_defaults(func=lambda args: cmd_install(argparse.Namespace(
        version=args.version_opt or args.version_pos,
        listen_address=args.listen_address, cluster_address=args.cluster_address,
        api_addr=args.api_addr, cluster_addr=args.cluster_addr,
        no_tls=args.no_tls, tls_auto=args.tls_auto, tls_cert_file=args.tls_cert_file,
        tls_key_file=args.tls_key_file, tls_ca_cert_file=args.tls_ca_cert_file,
        tls_dns=args.tls_dns, tls_ip=args.tls_ip, tls_common_name=args.tls_common_name,
    )))

    doctor = sub.add_parser(
        "doctor",
        description="Check the managed Vault install, the seal state and the init output.\n"
        "\n"
        "Read-only. It decodes a 501 or 503 health response into the command that fixes it,\n"
        "and fails when the init output is not 0600 root-owned, since it holds every unseal\n"
        "key and the root token.",
    )
    add_client_args(doctor)
    doctor.set_defaults(func=cmd_doctor)

    status = sub.add_parser(
        "status",
        description="Show what is configured on this node: versions, paths, service state, the\n"
        "effective config, the init output and finally 'vault status' itself.\n"
        "\n"
        "status answers \"what is it\"; doctor answers \"is it broken\". Neither changes anything.",
    )
    add_client_args(status)
    status.set_defaults(func=cmd_status)

    init = sub.add_parser(
        "init",
        description="Initialize Vault and save the unseal keys and root token.\n"
        "\n"
        "Vault returns them exactly once. The output file is the only copy, written 0600 and\n"
        f"root-owned at {DEFAULT_INIT_FILE};\n"
        "back it up before doing anything else. init also writes\n"
        f"{target_acl_file()} so your shell can reach Vault.\n"
        "\n"
        "Refuses to run against an initialized Vault, and refuses to overwrite an existing\n"
        "output file without --force.",
    )
    init.add_argument("--key-shares", type=int, default=5, help="Number of unseal key shares (default: 5)")
    init.add_argument("--key-threshold", type=int, default=3, help="Shares needed to unseal (default: 3)")
    init.add_argument("--out", default="", help=f"Init JSON output path (default: {DEFAULT_INIT_FILE})")
    init.add_argument("--force", action="store_true", help="Overwrite an existing output file")
    add_client_args(init)
    init.set_defaults(func=cmd_init)

    unseal = sub.add_parser(
        "unseal",
        description="Unseal Vault using the keys in the init JSON.\n"
        "\n"
        "Vault seals itself on every restart, so this is needed again after a reboot.\n"
        "Applies keys one at a time and stops as soon as Vault reports itself unsealed.\n"
        "A no-op when Vault is already unsealed.",
    )
    unseal.add_argument("--keys-file", required=True, help="Init JSON holding the unseal keys")
    add_client_args(unseal)
    unseal.set_defaults(func=cmd_unseal)

    auth = sub.add_parser(
        "auth",
        description="Manage Vault auth methods.\n"
        "\n"
        "enable is idempotent for the same type at the same path and fails when the path\n"
        "exists with a different type; disable is idempotent when the path is absent.\n"
        "\n"
        "KEY=VALUE arguments to write land in shell history and in this tool's audit log.\n"
        "Do not pass secrets that way.",
    )
    auth_sub = auth.add_subparsers(dest="auth_command")
    auth.set_defaults(func=lambda _: missing_subcommand(auth, f"{VAULT_MANAGER_CMD} auth"))
    auth_list = auth_sub.add_parser("list", help="Show enabled auth methods")
    add_client_args(auth_list)
    auth_list.set_defaults(func=cmd_auth_list)
    auth_enable = auth_sub.add_parser("enable", help="Enable an auth method")
    auth_enable.add_argument("type", help="Auth method type, for example jwt or userpass")
    auth_enable.add_argument("--path", default="", help="Mount path (default: the type name)")
    auth_enable.add_argument("--description", default="", help="Auth method description")
    auth_enable.add_argument("--default-lease-ttl", default="", help="Default lease TTL")
    auth_enable.add_argument("--max-lease-ttl", default="", help="Maximum lease TTL")
    add_client_args(auth_enable)
    auth_enable.set_defaults(func=cmd_auth_enable)
    auth_disable = auth_sub.add_parser("disable", help="Disable the auth method at a path")
    auth_disable.add_argument("path", help="Mount path")
    add_client_args(auth_disable)
    auth_disable.set_defaults(func=cmd_auth_disable)
    auth_read = auth_sub.add_parser("read", help="Read auth/<PATH>")
    auth_read.add_argument("path", help="Path under auth/")
    add_client_args(auth_read)
    auth_read.set_defaults(func=cmd_auth_read)
    auth_write = auth_sub.add_parser("write", help="Write KEY=VALUE pairs to auth/<PATH>")
    auth_write.add_argument("path", help="Path under auth/")
    auth_write.add_argument("pairs", nargs="*", help="KEY=VALUE pairs")
    add_client_args(auth_write)
    auth_write.set_defaults(func=cmd_auth_write)

    policy = sub.add_parser(
        "policy",
        description="Manage Vault policies from local HCL files.\n"
        "\n"
        "write is idempotent for identical content. Keep policy files in version control;\n"
        "Vault stores the text but not its history.",
    )
    policy_sub = policy.add_subparsers(dest="policy_command")
    policy.set_defaults(func=lambda _: missing_subcommand(policy, f"{VAULT_MANAGER_CMD} policy"))
    policy_list = policy_sub.add_parser("list", help="Show policy names")
    add_client_args(policy_list)
    policy_list.set_defaults(func=cmd_policy_list)
    policy_read = policy_sub.add_parser("read", help="Print a policy")
    policy_read.add_argument("name", help="Policy name")
    add_client_args(policy_read)
    policy_read.set_defaults(func=cmd_policy_read)
    policy_write = policy_sub.add_parser("write", help="Create or update a policy from a file")
    policy_write.add_argument("name", help="Policy name")
    policy_write.add_argument("file", help="Policy HCL file")
    add_client_args(policy_write)
    policy_write.set_defaults(func=cmd_policy_write)
    policy_delete = policy_sub.add_parser("delete", help="Delete a policy")
    policy_delete.add_argument("name", help="Policy name")
    add_client_args(policy_delete)
    policy_delete.set_defaults(func=cmd_policy_delete)

    upgrade = sub.add_parser(
        "upgrade",
        help="Install another Vault release and restart the server",
        description="Replace the Vault binary with another release and restart vault.service.\n"
        "\n"
        "Only the binary changes: config, TLS material, the raft store, the init output and\n"
        "the installed tool files are left alone. The replaced release stays on disk, so a\n"
        "server that fails to come back is switched to it again automatically.\n"
        "\n"
        "The restart seals Vault, so have the unseal keys at hand. Run --dry-run first to\n"
        "see the plan.",
    )
    add_client_args(upgrade)
    upgrade.add_argument("--version", default="latest", help="Target Vault version, or latest (default: latest)")
    upgrade.add_argument("--keep", type=int, default=2, metavar="N",
                         help="Releases to keep on disk, including the running one (default: 2)")
    upgrade.add_argument("--allow-downgrade", action="store_true", help="Allow installing an older release than the running one")
    upgrade.add_argument("--dry-run", action="store_true", help="Print the upgrade plan without changing anything")
    upgrade.add_argument("--yes", action="store_true", help="Skip the interactive confirmation")
    upgrade.set_defaults(func=cmd_upgrade)

    tools = sub.add_parser(
        "tools",
        description="Manage the installed vault-manager files without touching the Vault binary,\n"
        "config, service state or data.",
    )
    tools_sub = tools.add_subparsers(dest="tools_command")
    tools.set_defaults(func=lambda _: missing_subcommand(tools, f"{VAULT_MANAGER_CMD} tools"))
    tools_update = tools_sub.add_parser(
        "update",
        help="Update vault-manager files only",
        description="Refresh the tool copy that install placed on this node.\n"
        "\n"
        "The new files are read from the directory of the script you invoke, so run this from\n"
        f"a source checkout. Running the installed {TOOL_ENTRY} would copy\n"
        "the node's own copy onto itself and change nothing, so that is refused.",
    )
    tools_update.add_argument("--vault-version",
                              help="Vault version recorded in tool metadata; defaults to existing metadata. "
                                   "This only records a version, it does not change the binary: use upgrade for that")
    tools_update.set_defaults(func=cmd_tools_update)

    uninstall = sub.add_parser(
        "uninstall",
        description="Stop Vault and remove runtime files after showing a removal plan.\n"
        "\n"
        "Run --dry-run first. The default keeps the raft store and the init output, so the\n"
        "data and the unseal keys survive. --purge-data removes both, which destroys the\n"
        "raft store beyond recovery.",
    )
    uninstall.add_argument("--purge-data", action="store_true", help=f"Also remove {STATE_DIR} and {INIT_DIR}")
    uninstall.add_argument("--remove-tools", action="store_true", help="Also remove the installed vault-manager files")
    uninstall.add_argument("--purge", action="store_true", help="Remove runtime, state, init output, tools, metadata and audit logs")
    uninstall.add_argument("--dry-run", action="store_true", help="Print the uninstall plan without changing files")
    uninstall.add_argument("--yes", action="store_true", help="Skip the interactive confirmation")
    uninstall.set_defaults(func=cmd_uninstall)

    quickstart = sub.add_parser("quickstart", description="Show a copyable end-to-end setup workflow.")
    quickstart.set_defaults(func=cmd_quickstart)

    tutor = sub.add_parser("tutor", description="Show short workflow guidance for one topic.")
    tutor.add_argument("topic", nargs="?", help=f"Topic name: {', '.join(TUTOR_TOPICS)}")
    tutor.set_defaults(func=cmd_tutor)
    return parser


def dispatch(argv: list[str]) -> int:
    parser = build_parser()
    if argv and argv[0] == "help":
        argv = ["--help", *argv[1:]]
    args = parser.parse_args(argv)
    return int(args.func(args))


def main(argv: list[str] | None = None) -> int:
    ensure_default_path()
    config = AuditConfig("vault-manager", AUDIT_LOG_FILE, {"tool_dir": str(TOOL_DIR)})
    return run_with_audit(config, sys.argv[1:] if argv is None else argv, dispatch)
