[package]
name = "solana_program_tmpl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-program = "1.17.13"
thiserror = "1.0.53"

[lib]
name = "solana_program_tmpl"
crate-type = ["cdylib", "lib"]
