version: "3.9"
services:
  app:
    build: .
    ports:
      - "8000:8000"

    environment:
      RUST_LOG: info


# docker compose build --build-arg HTTP_PROXY=http://<HOST>:<PORT> --build-arg HTTP_PROXY=http://<HOST>:<PORT>
