version: "3"

services:
  btc:
    container_name: btc
    build:
      context: .
      dockerfile: Dockerfile
      # OR
      #dockerfile: Dockerfile-download
    ports:
      - "8338:8338/tcp"
      - "8890:8890/tcp"

    # environment:
      # WEBPASSWORD: 'mypass'

    volumes:
      - '/home/eagle/servers/btc/datadir:/app/datadir'
      # - './datadir:/app/datadir'
      - './bitcoin.conf:/app/bitcoin.conf'

    restart: always

    # 限制日志大小
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

