#!/bin/bash

SCRIPT_DIR="$(CDPATH='' cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
COMMON_LIB="${SCRIPT_DIR}/../lib/init-common.sh"
# shellcheck disable=SC2034
INIT_CALLER_SOURCE="${BASH_SOURCE[0]}"
# shellcheck source=../lib/init-common.sh
source "${COMMON_LIB}"
unset COMMON_LIB INIT_CALLER_SOURCE

# ------------------------------------------------------------
# 子命令数组
# shellcheck disable=SC2034
COMMANDS=("help" "check" "install" "uninstall")
# shellcheck disable=SC2034
HELP_OPTIONS=("-l LOG_LEVEL  Set the log level (FATAL ERROR, WARNING, INFO, SUCCESS, DEBUG)")

show_help() {
    _show_standard_help "$0 [-l LOG_LEVEL] <command>" COMMANDS HELP_OPTIONS
}

ZSH=${ZSH:-${INIT_TARGET_HOME}/.oh-my-zsh}
ZSH_CUSTOM=${ZSH_CUSTOM:-${ZSH}/custom}
STATE_DIR="${INIT_TARGET_HOME}/.local/state/init"
STATE_FILE="${STATE_DIR}/zsh.state"
ZSHRC_LINK_TARGET="${INIT_REPO_ROOT}/softlinks/zshrc"
SSH_CONFIG="${INIT_TARGET_HOME}/.ssh/config"
SSH_CONFIG_MARKER="# managed-by: init/sshconfig"
SSH_CONFIG_LEGACY_LINK_TARGET="${INIT_REPO_ROOT}/softlinks/sshconfig"
SSH_CONFIG_LOCAL_INCLUDE="${INIT_REPO_ROOT}/softlinks/sshconfig.local"
SSH_CONFIG_SHARED_INCLUDE="${INIT_REPO_ROOT}/softlinks/sshconfig.shared"
AUTOSUGGESTIONS_DIR="${ZSH_CUSTOM}/plugins/zsh-autosuggestions"
AUTOSUGGESTIONS_REPO="https://github.com/zsh-users/zsh-autosuggestions"
SYNTAX_HIGHLIGHTING_DIR="${ZSH_CUSTOM}/plugins/zsh-syntax-highlighting"
SYNTAX_HIGHLIGHTING_REPO="https://github.com/zsh-users/zsh-syntax-highlighting.git"
EDITRC_MARKER_BEGIN="# BEGIN managed by init:zsh"
EDITRC_MARKER_END="# END managed by init:zsh"
INPUTRC_MARKER_BEGIN="# BEGIN managed by init:zsh"
INPUTRC_MARKER_END="# END managed by init:zsh"

_ensure_state_dir() {
    mkdir -p "${STATE_DIR}"
}

_write_state() {
    _write_kv_file "${STATE_FILE}" \
        MANAGED_AUTOSUGGESTIONS_DIR "${1:-0}" \
        MANAGED_SYNTAX_HIGHLIGHTING_DIR "${2:-0}"
}

_state_get() {
    local key="${1:?missing state key}"
    _kv_file_get "${STATE_FILE}" "${key}"
}

_cleanup_state_file() {
    [ -f "${STATE_FILE}" ] && /bin/rm -f "${STATE_FILE}"
}

_ensure_managed_block() {
    local file="${1:?missing file}"
    local begin="${2:?missing begin marker}"
    local end="${3:?missing end marker}"
    local body="${4:?missing body}"

    [ -f "${file}" ] || touch "${file}"

    if grep -Fq "${begin}" "${file}" || grep -Fxq "${body}" "${file}"; then
        return 0
    fi

    cat >>"${file}" <<EOF
${begin}
${body}
${end}
EOF
}

_remove_managed_block() {
    local file="${1:?missing file}"
    local begin="${2:?missing begin marker}"
    local end="${3:?missing end marker}"
    local tmp_file

    [ -f "${file}" ] || return 0
    grep -Fq "${begin}" "${file}" || return 0

    tmp_file="$(mktemp "${TMPDIR:-/tmp}/init-zsh.XXXXXX")" || return 1
    awk -v begin="${begin}" -v end="${end}" '
        $0 == begin { skip = 1; next }
        $0 == end { skip = 0; next }
        skip != 1 { print }
    ' "${file}" >"${tmp_file}" && mv "${tmp_file}" "${file}"

    if [ ! -s "${file}" ]; then
        /bin/rm -f "${file}"
    fi
}

_remove_symlink_if_matches() {
    local path="${1:?missing path}"
    local expected_target="${2:?missing expected target}"

    if _path_matches_target "${path}" "${expected_target}"; then
        /bin/rm -f "${path}"
    fi
}

_write_ssh_config() {
    local tmp_file

    tmp_file="$(mktemp "${TMPDIR:-/tmp}/init-sshconfig.XXXXXX")" || return 1
    cat >"${tmp_file}" <<EOF
${SSH_CONFIG_MARKER}
# Generated by init. Re-run scripts/zsh.sh install if this repo moves.
Include ${SSH_CONFIG_LOCAL_INCLUDE}
Include ~/.ssh/config.local
Include ${SSH_CONFIG_SHARED_INCLUDE}
EOF

    if { [ -e "${SSH_CONFIG}" ] || [ -L "${SSH_CONFIG}" ]; } && ! grep -Fqx "${SSH_CONFIG_MARKER}" "${SSH_CONFIG}" 2>/dev/null && ! _files_match "${SSH_CONFIG}" "${tmp_file}"; then
        _backup_existing_path "${SSH_CONFIG}"
    fi

    if [ ! -f "${SSH_CONFIG}" ] || ! _files_match "${SSH_CONFIG}" "${tmp_file}"; then
        _ensure_parent_dir "${SSH_CONFIG}"
        mv "${tmp_file}" "${SSH_CONFIG}"
    else
        /bin/rm -f "${tmp_file}"
    fi
}

_remove_managed_file_if_marked() {
    local path="${1:?missing path}"
    local marker="${2:?missing marker}"

    [ -f "${path}" ] || return 0
    grep -Fqx "${marker}" "${path}" || return 0
    /bin/rm -f "${path}"
}

_remove_plugin_dir_if_managed() {
    local repo_dir="${1:?missing repo dir}"
    local expected_remote="${2:?missing expected remote}"
    local state_key="${3:?missing state key}"

    [ "$(_state_get "${state_key}")" = "1" ] || return 0
    [ -d "${repo_dir}" ] || return 0

    if _git_remote_matches "${repo_dir}" "${expected_remote}"; then
        /bin/rm -rf "${repo_dir}"
    fi
}

_remove_repo_theme_symlinks() {
    local theme_source
    local theme_name
    local theme_target

    for theme_source in "${SCRIPT_DIR}"/../softlinks/*.zsh-theme; do
        [ -e "${theme_source}" ] || continue
        theme_name="$(basename "${theme_source}")"
        theme_target="${ZSH_CUSTOM}/themes/${theme_name}"
        _remove_symlink_if_matches "${theme_target}" "${theme_source}"
    done
}

_link_repo_theme_symlinks() {
    local theme_source
    local theme_name
    local theme_target

    for theme_source in "${SCRIPT_DIR}"/../softlinks/*.zsh-theme; do
        [ -e "${theme_source}" ] || continue
        theme_name="$(basename "${theme_source}")"
        theme_target="${ZSH_CUSTOM}/themes/${theme_name}"
        _ensure_symlink "${theme_source}" "${theme_target}"
    done
}

check() {
    _require_commands git curl zsh
}

install() {
    export SHELLRC_ROOT="${INIT_REPO_ROOT}/shellConfigs"
    check
    set -e
    local managed_autosuggestions_dir=0
    local managed_syntax_highlighting_dir=0

    [ "$(_state_get MANAGED_AUTOSUGGESTIONS_DIR)" = "1" ] && managed_autosuggestions_dir=1
    [ "$(_state_get MANAGED_SYNTAX_HIGHLIGHTING_DIR)" = "1" ] && managed_syntax_highlighting_dir=1

    _ensure_managed_block "${INIT_TARGET_HOME}/.editrc" "${EDITRC_MARKER_BEGIN}" "${EDITRC_MARKER_END}" "bind -v"
    _ensure_managed_block "${INIT_TARGET_HOME}/.inputrc" "${INPUTRC_MARKER_BEGIN}" "${INPUTRC_MARKER_END}" "set editing-mode vi"

    # install omz
    if [ -f "${ZSH}/oh-my-zsh.sh" ]; then
        log INFO "oh-my-zsh already exists at ${ZSH}, skip installer"
    else
        (
            cd /tmp
            local installer
            installer="omzInstaller-$(date +%s).sh"
            curl -fsSL -o "${installer}" https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
            RUNZSH=no bash "${installer}"
        )
    fi

    _ensure_symlink "${ZSHRC_LINK_TARGET}" "${INIT_TARGET_HOME}/.zshrc" || {
        echo "Please fork the repo first"
        exit 1
    }

    _ensureDir "${ZSH_CUSTOM}/themes" "${ZSH_CUSTOM}/plugins" "${INIT_TARGET_HOME}/.ssh"

    # omz plugins
    # zsh-autosuggestions
    if [ ! -d "${AUTOSUGGESTIONS_DIR}" ]; then
        git clone "${AUTOSUGGESTIONS_REPO}" "${AUTOSUGGESTIONS_DIR}"
        managed_autosuggestions_dir=1
    elif _git_remote_matches "${AUTOSUGGESTIONS_DIR}" "${AUTOSUGGESTIONS_REPO}"; then
        log INFO "${AUTOSUGGESTIONS_DIR} already exists, skip clone"
    else
        log WARNING "${AUTOSUGGESTIONS_DIR} exists and is not the expected repo, skip clone"
    fi
    # zsh-syntax-highlighting
    if [ ! -d "${SYNTAX_HIGHLIGHTING_DIR}" ]; then
        git clone "${SYNTAX_HIGHLIGHTING_REPO}" "${SYNTAX_HIGHLIGHTING_DIR}"
        managed_syntax_highlighting_dir=1
    elif _git_remote_matches "${SYNTAX_HIGHLIGHTING_DIR}" "${SYNTAX_HIGHLIGHTING_REPO}"; then
        log INFO "${SYNTAX_HIGHLIGHTING_DIR} already exists, skip clone"
    else
        log WARNING "${SYNTAX_HIGHLIGHTING_DIR} exists and is not the expected repo, skip clone"
    fi

    # custom theme
    _link_repo_theme_symlinks

    _write_ssh_config

    _write_state "${managed_autosuggestions_dir}" "${managed_syntax_highlighting_dir}"
}

uninstall() {
    _remove_symlink_if_matches "${INIT_TARGET_HOME}/.zshrc" "${ZSHRC_LINK_TARGET}"
    _remove_managed_file_if_marked "${SSH_CONFIG}" "${SSH_CONFIG_MARKER}"
    _remove_symlink_if_matches "${SSH_CONFIG}" "${SSH_CONFIG_LEGACY_LINK_TARGET}"
    _remove_repo_theme_symlinks
    _remove_plugin_dir_if_managed "${AUTOSUGGESTIONS_DIR}" "${AUTOSUGGESTIONS_REPO}" "MANAGED_AUTOSUGGESTIONS_DIR"
    _remove_plugin_dir_if_managed "${SYNTAX_HIGHLIGHTING_DIR}" "${SYNTAX_HIGHLIGHTING_REPO}" "MANAGED_SYNTAX_HIGHLIGHTING_DIR"
    _remove_managed_block "${INIT_TARGET_HOME}/.editrc" "${EDITRC_MARKER_BEGIN}" "${EDITRC_MARKER_END}"
    _remove_managed_block "${INIT_TARGET_HOME}/.inputrc" "${INPUTRC_MARKER_BEGIN}" "${INPUTRC_MARKER_END}"
    _cleanup_state_file
}


_dispatch_cli show_help _resolve_cli_handler "$@"
