version: '3.1'

services:
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 13306:80
    environment:
      # 1. 要么 支持任意mysql，打开web时指定mysql host
      - PMA_ARBITRARY=1
      # 2. 要么 指定mysql ip 
      # - PMA_HOST=<MYSQL_HOST>
